//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Recursos", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abierta.
        /// </summary>
        internal static string Abierta {
            get {
                return ResourceManager.GetString("Abierta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acta.
        /// </summary>
        internal static string Acta {
            get {
                return ResourceManager.GetString("Acta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acta de Origen.
        /// </summary>
        internal static string ActaOrigen {
            get {
                return ResourceManager.GetString("ActaOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actas.
        /// </summary>
        internal static string Actas {
            get {
                return ResourceManager.GetString("Actas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48.
        /// </summary>
        internal static string ActivarAutonumeracionLegajo {
            get {
                return ResourceManager.GetString("ActivarAutonumeracionLegajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVA_DESIGNACIONES.
        /// </summary>
        internal static string ActivarDesignaciones {
            get {
                return ResourceManager.GetString("ActivarDesignaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52.
        /// </summary>
        internal static string ActivarInterfaz {
            get {
                return ResourceManager.GetString("ActivarInterfaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVA_NOMENCLATURAS.
        /// </summary>
        internal static string ActivarNomenclaturas {
            get {
                return ResourceManager.GetString("ActivarNomenclaturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVA_PARTIDAS.
        /// </summary>
        internal static string ActivarPartidas {
            get {
                return ResourceManager.GetString("ActivarPartidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVA_VALUACIONES.
        /// </summary>
        internal static string ActivarValuaciones {
            get {
                return ResourceManager.GetString("ActivarValuaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVA_ZONIFICACION.
        /// </summary>
        internal static string ActivarZonificacion {
            get {
                return ResourceManager.GetString("ActivarZonificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expedientes de Obra.
        /// </summary>
        internal static string AdministracionExpedientesObra {
            get {
                return ResourceManager.GetString("AdministracionExpedientesObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Inspectores.
        /// </summary>
        internal static string AdministracionInspectores {
            get {
                return ResourceManager.GetString("AdministracionInspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Ploteos Predefinidos.
        /// </summary>
        internal static string AdministracionPloteosPredefinidos {
            get {
                return ResourceManager.GetString("AdministracionPloteosPredefinidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta Alfanumérica de Parcelas.
        /// </summary>
        internal static string AlfanumericoParcela {
            get {
                return ResourceManager.GetString("AlfanumericoParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generador de Analisis Predefinido.
        /// </summary>
        internal static string AnalisisPredefinido {
            get {
                return ResourceManager.GetString("AnalisisPredefinido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo.
        /// </summary>
        internal static string Archivo {
            get {
                return ResourceManager.GetString("Archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atributos por Zona.
        /// </summary>
        internal static string AtributosZona {
            get {
                return ResourceManager.GetString("AtributosZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsqueda.
        /// </summary>
        internal static string Busqueda {
            get {
                return ResourceManager.GetString("Busqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendario.
        /// </summary>
        internal static string Calendario {
            get {
                return ResourceManager.GetString("Calendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Contraseña.
        /// </summary>
        internal static string CambiarContraseña {
            get {
                return ResourceManager.GetString("CambiarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        internal static string CambioMunicipio {
            get {
                return ResourceManager.GetString("CambioMunicipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracteristicas del Inspector.
        /// </summary>
        internal static string CaracteristicasInspector {
            get {
                return ResourceManager.GetString("CaracteristicasInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoSystems S.A.
        /// </summary>
        internal static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato del archivo seleccionado inválido..
        /// </summary>
        internal static string ColeccionController_ImportarArchivoColeccion_FormatoInvalido {
            get {
                return ResourceManager.GetString("ColeccionController_ImportarArchivoColeccion_FormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre [{0}] ya existe, por favor ingrese uno nuevo..
        /// </summary>
        internal static string ColeccionController_NombreColeccionExistente {
            get {
                return ResourceManager.GetString("ColeccionController_NombreColeccionExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        internal static string Desde {
            get {
                return ResourceManager.GetString("Desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días.
        /// </summary>
        internal static string Dias {
            get {
                return ResourceManager.GetString("Dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanzador de Ploteos.
        /// </summary>
        internal static string DispatcherPloteos {
            get {
                return ResourceManager.GetString("DispatcherPloteos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNI.
        /// </summary>
        internal static string DNI {
            get {
                return ResourceManager.GetString("DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El DNI ingresado No corresponde a un usuario dado de alta..
        /// </summary>
        internal static string DNIInexistente {
            get {
                return ResourceManager.GetString("DNIInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos.
        /// </summary>
        internal static string Documentos {
            get {
                return ResourceManager.GetString("Documentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos y Referencias.
        /// </summary>
        internal static string DocumentosReferencias {
            get {
                return ResourceManager.GetString("DocumentosReferencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicilio/s.
        /// </summary>
        internal static string Domicilio {
            get {
                return ResourceManager.GetString("Domicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expediente de Obra.
        /// </summary>
        internal static string ExpedienteObra {
            get {
                return ResourceManager.GetString("ExpedienteObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 54.
        /// </summary>
        internal static string ExpedientesObraMostrarActas {
            get {
                return ResourceManager.GetString("ExpedientesObraMostrarActas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 47.
        /// </summary>
        internal static string ExpresionRegularChapa {
            get {
                return ResourceManager.GetString("ExpresionRegularChapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 78.
        /// </summary>
        internal static string ExpresionRegularChapaVisible {
            get {
                return ResourceManager.GetString("ExpresionRegularChapaVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45.
        /// </summary>
        internal static string ExpresionRegularExpediente {
            get {
                return ResourceManager.GetString("ExpresionRegularExpediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 76.
        /// </summary>
        internal static string ExpresionRegularExpedienteVisible {
            get {
                return ResourceManager.GetString("ExpresionRegularExpedienteVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 46.
        /// </summary>
        internal static string ExpresionRegularLegajo {
            get {
                return ResourceManager.GetString("ExpresionRegularLegajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 77.
        /// </summary>
        internal static string ExpresionRegularLegajoVisible {
            get {
                return ResourceManager.GetString("ExpresionRegularLegajoVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Alta.
        /// </summary>
        internal static string FechaAlta {
            get {
                return ResourceManager.GetString("FechaAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Desde.
        /// </summary>
        internal static string FechaDesde {
            get {
                return ResourceManager.GetString("FechaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Hasta.
        /// </summary>
        internal static string FechaHasta {
            get {
                return ResourceManager.GetString("FechaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y Hora.
        /// </summary>
        internal static string FechaHora {
            get {
                return ResourceManager.GetString("FechaHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y Hora.
        /// </summary>
        internal static string FechaHoraDesde {
            get {
                return ResourceManager.GetString("FechaHoraDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Hora hasta.
        /// </summary>
        internal static string FechaHoraHasta {
            get {
                return ResourceManager.GetString("FechaHoraHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y Hora Originales.
        /// </summary>
        internal static string FechaHoraOriginal {
            get {
                return ResourceManager.GetString("FechaHoraOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y Hora de Planificación.
        /// </summary>
        internal static string FechaHoraPlanificacion {
            get {
                return ResourceManager.GetString("FechaHoraPlanificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Origen desde.
        /// </summary>
        internal static string FechaOrigenDesde {
            get {
                return ResourceManager.GetString("FechaOrigenDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Origen hasta.
        /// </summary>
        internal static string FechaOrigenHasta {
            get {
                return ResourceManager.GetString("FechaOrigenHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechas.
        /// </summary>
        internal static string Fechas {
            get {
                return ResourceManager.GetString("Fechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizada.
        /// </summary>
        internal static string Finalizada {
            get {
                return ResourceManager.GetString("Finalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de Informes y Certificados.
        /// </summary>
        internal static string GeneracionCertificados {
            get {
                return ResourceManager.GetString("GeneracionCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al ingresar al sistema.
        /// </summary>
        internal static string GrupoInexistente {
            get {
                return ResourceManager.GetString("GrupoInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        internal static string Hasta {
            get {
                return ResourceManager.GetString("Hasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación.
        /// </summary>
        internal static string Identificacion {
            get {
                return ResourceManager.GetString("Identificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        internal static string Identificador {
            get {
                return ResourceManager.GetString("Identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe de Expedientes por Obras.
        /// </summary>
        internal static string InformeExpedienteObras {
            get {
                return ResourceManager.GetString("InformeExpedienteObras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe Detallado de Expedientes de Obra.
        /// </summary>
        internal static string InformeExpedienteObrasDetallado {
            get {
                return ResourceManager.GetString("InformeExpedienteObrasDetallado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe de Inspecciones por Periodo.
        /// </summary>
        internal static string InformeInspeccionesPorPeriodo {
            get {
                return ResourceManager.GetString("InformeInspeccionesPorPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe de Inspecciones por Tipo.
        /// </summary>
        internal static string InformeInspeccionesPorTipo {
            get {
                return ResourceManager.GetString("InformeInspeccionesPorTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspección de.
        /// </summary>
        internal static string InspeccionDe {
            get {
                return ResourceManager.GetString("InspeccionDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspector.
        /// </summary>
        internal static string Inspector {
            get {
                return ResourceManager.GetString("Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspectores.
        /// </summary>
        internal static string Inspectores {
            get {
                return ResourceManager.GetString("Inspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspectores Registrados.
        /// </summary>
        internal static string InspectoresRegistrados {
            get {
                return ResourceManager.GetString("InspectoresRegistrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha enviado un nuevo Password via Mail..
        /// </summary>
        internal static string MailRecuperoPassword {
            get {
                return ResourceManager.GetString("MailRecuperoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha enviado tu Usuario via Mail..
        /// </summary>
        internal static string MailRecuperoUsuario {
            get {
                return ResourceManager.GetString("MailRecuperoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento de datos de Infraestructura.
        /// </summary>
        internal static string MantenimientoInfraestructura {
            get {
                return ResourceManager.GetString("MantenimientoInfraestructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41.
        /// </summary>
        internal static string MostrarPadrónPartida {
            get {
                return ResourceManager.GetString("MostrarPadrónPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre / Razón Social.
        /// </summary>
        internal static string NombreRazonSocial {
            get {
                return ResourceManager.GetString("NombreRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro.
        /// </summary>
        internal static string Nro {
            get {
                return ResourceManager.GetString("Nro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro Acta.
        /// </summary>
        internal static string NroActa {
            get {
                return ResourceManager.GetString("NroActa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        internal static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objeto.
        /// </summary>
        internal static string Objeto {
            get {
                return ResourceManager.GetString("Objeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        internal static string Observaciones {
            get {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otros Objetos.
        /// </summary>
        internal static string OtrosObjetos {
            get {
                return ResourceManager.GetString("OtrosObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personas.
        /// </summary>
        internal static string Personas {
            get {
                return ResourceManager.GetString("Personas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planificación de la Inspección.
        /// </summary>
        internal static string PlanificacionInspeccion {
            get {
                return ResourceManager.GetString("PlanificacionInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planificación de Inspecciones.
        /// </summary>
        internal static string PlanificacionInspecciones {
            get {
                return ResourceManager.GetString("PlanificacionInspecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planificada.
        /// </summary>
        internal static string Planificada {
            get {
                return ResourceManager.GetString("Planificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planificador.
        /// </summary>
        internal static string Planificador {
            get {
                return ResourceManager.GetString("Planificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plazo.
        /// </summary>
        internal static string Plazo {
            get {
                return ResourceManager.GetString("Plazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plazo Cump..
        /// </summary>
        internal static string PlazoCump {
            get {
                return ResourceManager.GetString("PlazoCump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privadas.
        /// </summary>
        internal static string Privadas {
            get {
                return ResourceManager.GetString("Privadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Públicas.
        /// </summary>
        internal static string Publicas {
            get {
                return ResourceManager.GetString("Publicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relacionar con.
        /// </summary>
        internal static string RelacionarCon {
            get {
                return ResourceManager.GetString("RelacionarCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado.
        /// </summary>
        internal static string Resultado {
            get {
                return ResourceManager.GetString("Resultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado de la Inspección.
        /// </summary>
        internal static string ResultadoInspeccion {
            get {
                return ResourceManager.GetString("ResultadoInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        internal static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al intentar conectar con el servicio de ruteo. Verifique la conexión a internet e intente nuevamente..
        /// </summary>
        internal static string RuteoErrorEnConexion {
            get {
                return ResourceManager.GetString("RuteoErrorEnConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 76.
        /// </summary>
        internal static string ServiciosComarcal {
            get {
                return ResourceManager.GetString("ServiciosComarcal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Acta.
        /// </summary>
        internal static string TipoActa {
            get {
                return ResourceManager.GetString("TipoActa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Acta.
        /// </summary>
        internal static string TipoDeActa {
            get {
                return ResourceManager.GetString("TipoDeActa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Inspección.
        /// </summary>
        internal static string TipoInspeccion {
            get {
                return ResourceManager.GetString("TipoInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABM Feriado.
        /// </summary>
        internal static string TituloFeriados {
            get {
                return ResourceManager.GetString("TituloFeriados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de Inspecciones.
        /// </summary>
        internal static string TituloGestionInspecciones {
            get {
                return ResourceManager.GetString("TituloGestionInspecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABM Horario.
        /// </summary>
        internal static string TituloHorarios {
            get {
                return ResourceManager.GetString("TituloHorarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapas Temáticos.
        /// </summary>
        internal static string TituloMapaTematico {
            get {
                return ResourceManager.GetString("TituloMapaTematico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVISO.
        /// </summary>
        internal static string TituloMensajesAviso {
            get {
                return ResourceManager.GetString("TituloMensajesAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        internal static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tramites.
        /// </summary>
        internal static string Tramites {
            get {
                return ResourceManager.GetString("Tramites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidades Tributarias.
        /// </summary>
        internal static string UnidadesTributarias {
            get {
                return ResourceManager.GetString("UnidadesTributarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad Tributaria.
        /// </summary>
        internal static string UnidadTributaria {
            get {
                return ResourceManager.GetString("UnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*) Usuario desactivado.
        /// </summary>
        internal static string UsuarioDesactivo {
            get {
                return ResourceManager.GetString("UsuarioDesactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al ingresar al sistema.
        /// </summary>
        internal static string UsuarioInexistente {
            get {
                return ResourceManager.GetString("UsuarioInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 39.
        /// </summary>
        internal static string ValidarNumeroExpediente {
            get {
                return ResourceManager.GetString("ValidarNumeroExpediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vencida.
        /// </summary>
        internal static string Vencida {
            get {
                return ResourceManager.GetString("Vencida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34.
        /// </summary>
        internal static string ZonaPlanificacion {
            get {
                return ResourceManager.GetString("ZonaPlanificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zonas.
        /// </summary>
        internal static string Zonas {
            get {
                return ResourceManager.GetString("Zonas", resourceCulture);
            }
        }
    }
}
