//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Seguridad {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Seguridad() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Seguridad", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 236.
        /// </summary>
        internal static string ABMdeActas {
            get {
                return ResourceManager.GetString("ABMdeActas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 118.
        /// </summary>
        internal static string ABMdeExpedientesdeObra {
            get {
                return ResourceManager.GetString("ABMdeExpedientesdeObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 244.
        /// </summary>
        internal static string ABMdePersonas {
            get {
                return ResourceManager.GetString("ABMdePersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 262.
        /// </summary>
        internal static string ABMDocumentos {
            get {
                return ResourceManager.GetString("ABMDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 120.
        /// </summary>
        internal static string ABMDomicilios {
            get {
                return ResourceManager.GetString("ABMDomicilios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 282.
        /// </summary>
        internal static string ABMPersonas {
            get {
                return ResourceManager.GetString("ABMPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 257.
        /// </summary>
        internal static string ABMProfesion {
            get {
                return ResourceManager.GetString("ABMProfesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 129.
        /// </summary>
        internal static string AccederalMantenedorparcelario {
            get {
                return ResourceManager.GetString("AccederalMantenedorparcelario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 119.
        /// </summary>
        internal static string Actas {
            get {
                return ResourceManager.GetString("Actas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 347.
        /// </summary>
        internal static string ActualizacionObjetoAdministrativo {
            get {
                return ResourceManager.GetString("ActualizacionObjetoAdministrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 338.
        /// </summary>
        internal static string ActualizacionPadrones {
            get {
                return ResourceManager.GetString("ActualizacionPadrones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 617.
        /// </summary>
        internal static string AdministracionDDJJ {
            get {
                return ResourceManager.GetString("AdministracionDDJJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 47.
        /// </summary>
        internal static string AdministraciondeFeriados {
            get {
                return ResourceManager.GetString("AdministraciondeFeriados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 43.
        /// </summary>
        internal static string AdministraciondeHorarios {
            get {
                return ResourceManager.GetString("AdministraciondeHorarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 39.
        /// </summary>
        internal static string AdministraciondePerfiles {
            get {
                return ResourceManager.GetString("AdministraciondePerfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 51.
        /// </summary>
        internal static string AdministraciondeTablasAuxiliares {
            get {
                return ResourceManager.GetString("AdministraciondeTablasAuxiliares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 35.
        /// </summary>
        internal static string AdministraciondeUsuarios {
            get {
                return ResourceManager.GetString("AdministraciondeUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 602.
        /// </summary>
        internal static string AdministracionValuacion {
            get {
                return ResourceManager.GetString("AdministracionValuacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 17.
        /// </summary>
        internal static string AgregarControlesTecnicos {
            get {
                return ResourceManager.GetString("AgregarControlesTecnicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5.
        /// </summary>
        internal static string AgregarExpedienteObra {
            get {
                return ResourceManager.GetString("AgregarExpedienteObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 48.
        /// </summary>
        internal static string AgregarFeriados {
            get {
                return ResourceManager.GetString("AgregarFeriados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 13.
        /// </summary>
        internal static string AgregarLiquidaciones {
            get {
                return ResourceManager.GetString("AgregarLiquidaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 20.
        /// </summary>
        internal static string AgregarObservaciones {
            get {
                return ResourceManager.GetString("AgregarObservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 9.
        /// </summary>
        internal static string AgregarPlanos {
            get {
                return ResourceManager.GetString("AgregarPlanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 24.
        /// </summary>
        internal static string AgregarSuperficies {
            get {
                return ResourceManager.GetString("AgregarSuperficies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 52.
        /// </summary>
        internal static string AgregarTablasAux {
            get {
                return ResourceManager.GetString("AgregarTablasAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 105.
        /// </summary>
        internal static string AltaAlfanumericodeParcelasyPosesiones {
            get {
                return ResourceManager.GetString("AltaAlfanumericodeParcelasyPosesiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 195.
        /// </summary>
        internal static string AltaAtributo {
            get {
                return ResourceManager.GetString("AltaAtributo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 213.
        /// </summary>
        internal static string AltaCertificados {
            get {
                return ResourceManager.GetString("AltaCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 182.
        /// </summary>
        internal static string AltaControlTecnico {
            get {
                return ResourceManager.GetString("AltaControlTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 239.
        /// </summary>
        internal static string AltadeActas {
            get {
                return ResourceManager.GetString("AltadeActas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 252.
        /// </summary>
        internal static string AltadeDomicilio {
            get {
                return ResourceManager.GetString("AltadeDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 227.
        /// </summary>
        internal static string AltadeInspeccion {
            get {
                return ResourceManager.GetString("AltadeInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 231.
        /// </summary>
        internal static string Altadeinspectores {
            get {
                return ResourceManager.GetString("Altadeinspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 123.
        /// </summary>
        internal static string AltadeParcelasDestino {
            get {
                return ResourceManager.GetString("AltadeParcelasDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 122.
        /// </summary>
        internal static string AltadeParcelasOrigen {
            get {
                return ResourceManager.GetString("AltadeParcelasOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 246.
        /// </summary>
        internal static string AltadePersonas {
            get {
                return ResourceManager.GetString("AltadePersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 259.
        /// </summary>
        internal static string AltadeProfesion {
            get {
                return ResourceManager.GetString("AltadeProfesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 269.
        /// </summary>
        internal static string Altaderegistros {
            get {
                return ResourceManager.GetString("Altaderegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 202.
        /// </summary>
        internal static string AltadeResultadodeBusqueda {
            get {
                return ResourceManager.GetString("AltadeResultadodeBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 497.
        /// </summary>
        internal static string AltaDesignaciones {
            get {
                return ResourceManager.GetString("AltaDesignaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 218.
        /// </summary>
        internal static string AltadeTramites {
            get {
                return ResourceManager.GetString("AltadeTramites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 172.
        /// </summary>
        internal static string AltaDocumento {
            get {
                return ResourceManager.GetString("AltaDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 620.
        /// </summary>
        internal static string AltaDocumentoMensura {
            get {
                return ResourceManager.GetString("AltaDocumentoMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 136.
        /// </summary>
        internal static string AltaDocumentosParcela {
            get {
                return ResourceManager.GetString("AltaDocumentosParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 149.
        /// </summary>
        internal static string AltaDocumentosUnidadTributaria {
            get {
                return ResourceManager.GetString("AltaDocumentosUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 142.
        /// </summary>
        internal static string AltaDomicilio {
            get {
                return ResourceManager.GetString("AltaDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 152.
        /// </summary>
        internal static string AltaDominio {
            get {
                return ResourceManager.GetString("AltaDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 166.
        /// </summary>
        internal static string AltaEstado {
            get {
                return ResourceManager.GetString("AltaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 158.
        /// </summary>
        internal static string AltaExpedientesObra {
            get {
                return ResourceManager.GetString("AltaExpedientesObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 44.
        /// </summary>
        internal static string AltaHorario {
            get {
                return ResourceManager.GetString("AltaHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 181.
        /// </summary>
        internal static string AltaInspeccion {
            get {
                return ResourceManager.GetString("AltaInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 178.
        /// </summary>
        internal static string AltaLiquidacion {
            get {
                return ResourceManager.GetString("AltaLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 312.
        /// </summary>
        internal static string AltaMantenedorUnidadTributaria {
            get {
                return ResourceManager.GetString("AltaMantenedorUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 607.
        /// </summary>
        internal static string AltaMensura {
            get {
                return ResourceManager.GetString("AltaMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 133.
        /// </summary>
        internal static string AltaNomenclatura {
            get {
                return ResourceManager.GetString("AltaNomenclatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 185.
        /// </summary>
        internal static string AltaObservacion {
            get {
                return ResourceManager.GetString("AltaObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 610.
        /// </summary>
        internal static string AltaParcelasMensura {
            get {
                return ResourceManager.GetString("AltaParcelasMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 40.
        /// </summary>
        internal static string AltaPerfil {
            get {
                return ResourceManager.GetString("AltaPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 175.
        /// </summary>
        internal static string AltaPersona {
            get {
                return ResourceManager.GetString("AltaPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 145.
        /// </summary>
        internal static string AltaResponsableFiscal {
            get {
                return ResourceManager.GetString("AltaResponsableFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 168.
        /// </summary>
        internal static string AltaSuperficie {
            get {
                return ResourceManager.GetString("AltaSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 155.
        /// </summary>
        internal static string AltaTitular {
            get {
                return ResourceManager.GetString("AltaTitular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 163.
        /// </summary>
        internal static string AltaUbicacionObra {
            get {
                return ResourceManager.GetString("AltaUbicacionObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 161.
        /// </summary>
        internal static string AltaUnidadesTributarias {
            get {
                return ResourceManager.GetString("AltaUnidadesTributarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 36.
        /// </summary>
        internal static string AltaUsuario {
            get {
                return ResourceManager.GetString("AltaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 250.
        /// </summary>
        internal static string AMBDomicilio {
            get {
                return ResourceManager.GetString("AMBDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 112.
        /// </summary>
        internal static string AsociaciondeParcelasGraficasyAlfanumericas {
            get {
                return ResourceManager.GetString("AsociaciondeParcelasGraficasyAlfanumericas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 102.
        /// </summary>
        internal static string Auditoria {
            get {
                return ResourceManager.GetString("Auditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 215.
        /// </summary>
        internal static string BajaCertificados {
            get {
                return ResourceManager.GetString("BajaCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 183.
        /// </summary>
        internal static string BajaControlTecnico {
            get {
                return ResourceManager.GetString("BajaControlTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 241.
        /// </summary>
        internal static string Bajadeactas {
            get {
                return ResourceManager.GetString("Bajadeactas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 197.
        /// </summary>
        internal static string BajadeAtributos {
            get {
                return ResourceManager.GetString("BajadeAtributos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 254.
        /// </summary>
        internal static string BajadeDomicilio {
            get {
                return ResourceManager.GetString("BajadeDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 229.
        /// </summary>
        internal static string BajadeInspeccion {
            get {
                return ResourceManager.GetString("BajadeInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 232.
        /// </summary>
        internal static string Bajadeinspectores {
            get {
                return ResourceManager.GetString("Bajadeinspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 177.
        /// </summary>
        internal static string BajadeLiquidacion {
            get {
                return ResourceManager.GetString("BajadeLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 125.
        /// </summary>
        internal static string BajadeParcelasDestino {
            get {
                return ResourceManager.GetString("BajadeParcelasDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 124.
        /// </summary>
        internal static string BajadeParcelasOrigen {
            get {
                return ResourceManager.GetString("BajadeParcelasOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 248.
        /// </summary>
        internal static string BajadePersonas {
            get {
                return ResourceManager.GetString("BajadePersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 478.
        /// </summary>
        internal static string BajadePlantilla {
            get {
                return ResourceManager.GetString("BajadePlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 261.
        /// </summary>
        internal static string BajadeProfesion {
            get {
                return ResourceManager.GetString("BajadeProfesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 271.
        /// </summary>
        internal static string BajadeRegistros {
            get {
                return ResourceManager.GetString("BajadeRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 204.
        /// </summary>
        internal static string BajadeResultadodeBusqueda {
            get {
                return ResourceManager.GetString("BajadeResultadodeBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 498.
        /// </summary>
        internal static string BajaDesignaciones {
            get {
                return ResourceManager.GetString("BajaDesignaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 220.
        /// </summary>
        internal static string BajadeTramite {
            get {
                return ResourceManager.GetString("BajadeTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 173.
        /// </summary>
        internal static string BajaDocumento {
            get {
                return ResourceManager.GetString("BajaDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 621.
        /// </summary>
        internal static string BajaDocumentoMesnsura {
            get {
                return ResourceManager.GetString("BajaDocumentoMesnsura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 138.
        /// </summary>
        internal static string BajaDocumentosParcela {
            get {
                return ResourceManager.GetString("BajaDocumentosParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 151.
        /// </summary>
        internal static string BajaDocumentosUnidadTributaria {
            get {
                return ResourceManager.GetString("BajaDocumentosUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 144.
        /// </summary>
        internal static string BajaDomicilio {
            get {
                return ResourceManager.GetString("BajaDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 154.
        /// </summary>
        internal static string BajaDominio {
            get {
                return ResourceManager.GetString("BajaDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 189.
        /// </summary>
        internal static string BajaExpedientedeObra {
            get {
                return ResourceManager.GetString("BajaExpedientedeObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 159.
        /// </summary>
        internal static string BajaExpedientesObra {
            get {
                return ResourceManager.GetString("BajaExpedientesObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 179.
        /// </summary>
        internal static string BajaLiquidacion {
            get {
                return ResourceManager.GetString("BajaLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 313.
        /// </summary>
        internal static string BajaMantenedorUnidadTributaria {
            get {
                return ResourceManager.GetString("BajaMantenedorUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 609.
        /// </summary>
        internal static string BajaMensura {
            get {
                return ResourceManager.GetString("BajaMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 135.
        /// </summary>
        internal static string BajaNomenclatura {
            get {
                return ResourceManager.GetString("BajaNomenclatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 186.
        /// </summary>
        internal static string BajaObservacion {
            get {
                return ResourceManager.GetString("BajaObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 176.
        /// </summary>
        internal static string BajaPersona {
            get {
                return ResourceManager.GetString("BajaPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 147.
        /// </summary>
        internal static string BajaResponsableFiscal {
            get {
                return ResourceManager.GetString("BajaResponsableFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 169.
        /// </summary>
        internal static string BajaSuperficie {
            get {
                return ResourceManager.GetString("BajaSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 157.
        /// </summary>
        internal static string BajaTitular {
            get {
                return ResourceManager.GetString("BajaTitular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 164.
        /// </summary>
        internal static string BajaUbicacionObra {
            get {
                return ResourceManager.GetString("BajaUbicacionObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 162.
        /// </summary>
        internal static string BajaUnidadesTributarias {
            get {
                return ResourceManager.GetString("BajaUnidadesTributarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 201.
        /// </summary>
        internal static string BusquedAlfanumericadeobjetosdeInfraestructura {
            get {
                return ResourceManager.GetString("BusquedAlfanumericadeobjetosdeInfraestructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 327.
        /// </summary>
        internal static string Catastro {
            get {
                return ResourceManager.GetString("Catastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 336.
        /// </summary>
        internal static string CatastroProvincial {
            get {
                return ResourceManager.GetString("CatastroProvincial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 495.
        /// </summary>
        internal static string CertificadoCatastral {
            get {
                return ResourceManager.GetString("CertificadoCatastral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 210.
        /// </summary>
        internal static string Certificados {
            get {
                return ResourceManager.GetString("Certificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 603.
        /// </summary>
        internal static string CertificadoValuatorio {
            get {
                return ResourceManager.GetString("CertificadoValuatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 284.
        /// </summary>
        internal static string ConexionCAD {
            get {
                return ResourceManager.GetString("ConexionCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 330.
        /// </summary>
        internal static string Configuracion {
            get {
                return ResourceManager.GetString("Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 216.
        /// </summary>
        internal static string ConfiguraciondeCertificados {
            get {
                return ResourceManager.GetString("ConfiguraciondeCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 33.
        /// </summary>
        internal static string ConfiguraciondeParametrosGenerales {
            get {
                return ResourceManager.GetString("ConfiguraciondeParametrosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 101.
        /// </summary>
        internal static string Consulta {
            get {
                return ResourceManager.GetString("Consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 333.
        /// </summary>
        internal static string ConsultadelPadron {
            get {
                return ResourceManager.GetString("ConsultadelPadron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 283.
        /// </summary>
        internal static string ConsultadeTramites {
            get {
                return ResourceManager.GetString("ConsultadeTramites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 320.
        /// </summary>
        internal static string ConsultarEstadoDeuda {
            get {
                return ResourceManager.GetString("ConsultarEstadoDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 601.
        /// </summary>
        internal static string DeclaracionesJuradas {
            get {
                return ResourceManager.GetString("DeclaracionesJuradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 476.
        /// </summary>
        internal static string DespublicarPlantilla {
            get {
                return ResourceManager.GetString("DespublicarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 321.
        /// </summary>
        internal static string EditarValuacion {
            get {
                return ResourceManager.GetString("EditarValuacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 352.
        /// </summary>
        internal static string EliminarBibliotecaBA {
            get {
                return ResourceManager.GetString("EliminarBibliotecaBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 349.
        /// </summary>
        internal static string EliminarBibliotecaMT {
            get {
                return ResourceManager.GetString("EliminarBibliotecaMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 19.
        /// </summary>
        internal static string EliminarControlesTecnicos {
            get {
                return ResourceManager.GetString("EliminarControlesTecnicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 7.
        /// </summary>
        internal static string EliminarExpedienteObra {
            get {
                return ResourceManager.GetString("EliminarExpedienteObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 50.
        /// </summary>
        internal static string EliminarFeriados {
            get {
                return ResourceManager.GetString("EliminarFeriados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 46.
        /// </summary>
        internal static string EliminarHorario {
            get {
                return ResourceManager.GetString("EliminarHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 117.
        /// </summary>
        internal static string EliminarInspectores {
            get {
                return ResourceManager.GetString("EliminarInspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 15.
        /// </summary>
        internal static string EliminarLiquidaciones {
            get {
                return ResourceManager.GetString("EliminarLiquidaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 22.
        /// </summary>
        internal static string EliminarObservaciones {
            get {
                return ResourceManager.GetString("EliminarObservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 111.
        /// </summary>
        internal static string EliminarParcelaDestino {
            get {
                return ResourceManager.GetString("EliminarParcelaDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 108.
        /// </summary>
        internal static string EliminarParcelaOrigen {
            get {
                return ResourceManager.GetString("EliminarParcelaOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 42.
        /// </summary>
        internal static string EliminarPerfil {
            get {
                return ResourceManager.GetString("EliminarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 11.
        /// </summary>
        internal static string EliminarPlanos {
            get {
                return ResourceManager.GetString("EliminarPlanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 26.
        /// </summary>
        internal static string EliminarSuperficies {
            get {
                return ResourceManager.GetString("EliminarSuperficies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 54.
        /// </summary>
        internal static string EliminarTablaAux {
            get {
                return ResourceManager.GetString("EliminarTablaAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 38.
        /// </summary>
        internal static string EliminarUsuarios {
            get {
                return ResourceManager.GetString("EliminarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4.
        /// </summary>
        internal static string ExpedientedeObra {
            get {
                return ResourceManager.GetString("ExpedientedeObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 324.
        /// </summary>
        internal static string ExportarCADAdmin {
            get {
                return ResourceManager.GetString("ExportarCADAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 325.
        /// </summary>
        internal static string ExportarCADUsuario {
            get {
                return ResourceManager.GetString("ExportarCADUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 211.
        /// </summary>
        internal static string GeneraciondeCertificados {
            get {
                return ResourceManager.GetString("GeneraciondeCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 209.
        /// </summary>
        internal static string GeneraciondeReportes {
            get {
                return ResourceManager.GetString("GeneraciondeReportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 104.
        /// </summary>
        internal static string Generarauditoria {
            get {
                return ResourceManager.GetString("Generarauditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 198.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 234.
        /// </summary>
        internal static string Guardarcambios {
            get {
                return ResourceManager.GetString("Guardarcambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 266.
        /// </summary>
        internal static string GuardarDocumentos {
            get {
                return ResourceManager.GetString("GuardarDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 255.
        /// </summary>
        internal static string GuardarDomicilio {
            get {
                return ResourceManager.GetString("GuardarDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 126.
        /// </summary>
        internal static string GuardarGeneral {
            get {
                return ResourceManager.GetString("GuardarGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 249.
        /// </summary>
        internal static string GuardarPersona {
            get {
                return ResourceManager.GetString("GuardarPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 272.
        /// </summary>
        internal static string Guardarregistros {
            get {
                return ResourceManager.GetString("Guardarregistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 243.
        /// </summary>
        internal static string Herramientas {
            get {
                return ResourceManager.GetString("Herramientas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 237.
        /// </summary>
        internal static string InformedeActaVencidasporPlazosOtorgados {
            get {
                return ResourceManager.GetString("InformedeActaVencidasporPlazosOtorgados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 199.
        /// </summary>
        internal static string InformedeAtributoporZona {
            get {
                return ResourceManager.GetString("InformedeAtributoporZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 224.
        /// </summary>
        internal static string InformedeInspeccionesporPeriodo {
            get {
                return ResourceManager.GetString("InformedeInspeccionesporPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 225.
        /// </summary>
        internal static string InformedeInspeccionesporTipodeInspeccion {
            get {
                return ResourceManager.GetString("InformedeInspeccionesporTipodeInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 206.
        /// </summary>
        internal static string InformedeObjetodeInfraestructura {
            get {
                return ResourceManager.GetString("InformedeObjetodeInfraestructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 113.
        /// </summary>
        internal static string InformedeSeguimientodeExpedientesdeO {
            get {
                return ResourceManager.GetString("InformedeSeguimientodeExpedientesdeO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 28.
        /// </summary>
        internal static string InformedeSeguimientodeExpedientesdeObra {
            get {
                return ResourceManager.GetString("InformedeSeguimientodeExpedientesdeObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 30.
        /// </summary>
        internal static string InformeEstadisticodeEdificacion {
            get {
                return ResourceManager.GetString("InformeEstadisticodeEdificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 311.
        /// </summary>
        internal static string InformeParcelario {
            get {
                return ResourceManager.GetString("InformeParcelario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 208.
        /// </summary>
        internal static string Informes {
            get {
                return ResourceManager.GetString("Informes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 316.
        /// </summary>
        internal static string InformeTributario {
            get {
                return ResourceManager.GetString("InformeTributario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 116.
        /// </summary>
        internal static string InsertarInspectores {
            get {
                return ResourceManager.GetString("InsertarInspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 110.
        /// </summary>
        internal static string InsertarParcelaDestino {
            get {
                return ResourceManager.GetString("InsertarParcelaDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 107.
        /// </summary>
        internal static string InsertarParcelaOrigen {
            get {
                return ResourceManager.GetString("InsertarParcelaOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 115.
        /// </summary>
        internal static string Inspecciones {
            get {
                return ResourceManager.GetString("Inspecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 334.
        /// </summary>
        internal static string InspeccionesSubmenu {
            get {
                return ResourceManager.GetString("InspeccionesSubmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 274.
        /// </summary>
        internal static string Instructivo {
            get {
                return ResourceManager.GetString("Instructivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 345.
        /// </summary>
        internal static string IntercambioCADconGeRED {
            get {
                return ResourceManager.GetString("IntercambioCADconGeRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 335.
        /// </summary>
        internal static string Interfaces {
            get {
                return ResourceManager.GetString("Interfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 275.
        /// </summary>
        internal static string LinksaOtrosSitiosdeInteres {
            get {
                return ResourceManager.GetString("LinksaOtrosSitiosdeInteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 276.
        /// </summary>
        internal static string Listadodetareasporusuarios {
            get {
                return ResourceManager.GetString("Listadodetareasporusuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 278.
        /// </summary>
        internal static string ListadodeUsuariosportareas {
            get {
                return ResourceManager.GetString("ListadodeUsuariosportareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 326.
        /// </summary>
        internal static string Loginexitoso {
            get {
                return ResourceManager.GetString("Loginexitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 114.
        /// </summary>
        internal static string MantenedorParcelario {
            get {
                return ResourceManager.GetString("MantenedorParcelario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 328.
        /// </summary>
        internal static string MantenimientodeAtributosysusValoresporZona {
            get {
                return ResourceManager.GetString("MantenimientodeAtributosysusValoresporZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 273.
        /// </summary>
        internal static string MantenimientodeCalles {
            get {
                return ResourceManager.GetString("MantenimientodeCalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 200.
        /// </summary>
        internal static string MantenimientodeDatosdeInfraestructura {
            get {
                return ResourceManager.GetString("MantenimientodeDatosdeInfraestructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 193.
        /// </summary>
        internal static string MantenimientodelCodigodePlaneamientoUrbano {
            get {
                return ResourceManager.GetString("MantenimientodelCodigodePlaneamientoUrbano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 329.
        /// </summary>
        internal static string MantenimientodeObjetosdeInfraestructura {
            get {
                return ResourceManager.GetString("MantenimientodeObjetosdeInfraestructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 267.
        /// </summary>
        internal static string MantenimientodeTablasAuxiliares {
            get {
                return ResourceManager.GetString("MantenimientodeTablasAuxiliares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 205.
        /// </summary>
        internal static string MapaderesultadodeBusqueda {
            get {
                return ResourceManager.GetString("MapaderesultadodeBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 253.
        /// </summary>
        internal static string ModifiarDomicilio {
            get {
                return ResourceManager.GetString("ModifiarDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 240.
        /// </summary>
        internal static string ModificaciondeActas {
            get {
                return ResourceManager.GetString("ModificaciondeActas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 196.
        /// </summary>
        internal static string ModificaciondeAtributos {
            get {
                return ResourceManager.GetString("ModificaciondeAtributos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 203.
        /// </summary>
        internal static string ModificaciondeResultadodeBusqueda {
            get {
                return ResourceManager.GetString("ModificaciondeResultadodeBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 160.
        /// </summary>
        internal static string ModificacionExpedientesObra {
            get {
                return ResourceManager.GetString("ModificacionExpedientesObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 608.
        /// </summary>
        internal static string ModificacionMensura {
            get {
                return ResourceManager.GetString("ModificacionMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 214.
        /// </summary>
        internal static string ModificarCertificados {
            get {
                return ResourceManager.GetString("ModificarCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 18.
        /// </summary>
        internal static string ModificarControlesTecnicos {
            get {
                return ResourceManager.GetString("ModificarControlesTecnicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 184.
        /// </summary>
        internal static string ModificarControlTecnico {
            get {
                return ResourceManager.GetString("ModificarControlTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 499.
        /// </summary>
        internal static string ModificarDesignaciones {
            get {
                return ResourceManager.GetString("ModificarDesignaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 174.
        /// </summary>
        internal static string ModificarDocumento {
            get {
                return ResourceManager.GetString("ModificarDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 622.
        /// </summary>
        internal static string ModificarDocumentoMensura {
            get {
                return ResourceManager.GetString("ModificarDocumentoMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 137.
        /// </summary>
        internal static string ModificarDocumentosParcela {
            get {
                return ResourceManager.GetString("ModificarDocumentosParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 150.
        /// </summary>
        internal static string ModificarDocumentosUnidadTributaria {
            get {
                return ResourceManager.GetString("ModificarDocumentosUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 143.
        /// </summary>
        internal static string ModificarDomicilio {
            get {
                return ResourceManager.GetString("ModificarDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 153.
        /// </summary>
        internal static string ModificarDominio {
            get {
                return ResourceManager.GetString("ModificarDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 167.
        /// </summary>
        internal static string ModificarEstado {
            get {
                return ResourceManager.GetString("ModificarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6.
        /// </summary>
        internal static string ModificarExpedienteObra {
            get {
                return ResourceManager.GetString("ModificarExpedienteObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 49.
        /// </summary>
        internal static string ModificarFeriados {
            get {
                return ResourceManager.GetString("ModificarFeriados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 45.
        /// </summary>
        internal static string ModificarHorarios {
            get {
                return ResourceManager.GetString("ModificarHorarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 228.
        /// </summary>
        internal static string ModificarInspeccion {
            get {
                return ResourceManager.GetString("ModificarInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 233.
        /// </summary>
        internal static string Modificarinspectores {
            get {
                return ResourceManager.GetString("Modificarinspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 180.
        /// </summary>
        internal static string ModificarLiquidacion {
            get {
                return ResourceManager.GetString("ModificarLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 14.
        /// </summary>
        internal static string ModificarLiquidaciones {
            get {
                return ResourceManager.GetString("ModificarLiquidaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 130.
        /// </summary>
        internal static string ModificarMantenedorParcelario {
            get {
                return ResourceManager.GetString("ModificarMantenedorParcelario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 314.
        /// </summary>
        internal static string ModificarMantenedorUnidadTributaria {
            get {
                return ResourceManager.GetString("ModificarMantenedorUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 134.
        /// </summary>
        internal static string ModificarNomenclatura {
            get {
                return ResourceManager.GetString("ModificarNomenclatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 188.
        /// </summary>
        internal static string ModificarObservacion {
            get {
                return ResourceManager.GetString("ModificarObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 21.
        /// </summary>
        internal static string ModificarObservaciones {
            get {
                return ResourceManager.GetString("ModificarObservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 34.
        /// </summary>
        internal static string ModificarParametrosGenerales {
            get {
                return ResourceManager.GetString("ModificarParametrosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 41.
        /// </summary>
        internal static string ModificarPerfil {
            get {
                return ResourceManager.GetString("ModificarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 247.
        /// </summary>
        internal static string ModificarPersonas {
            get {
                return ResourceManager.GetString("ModificarPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10.
        /// </summary>
        internal static string ModificarPlanos {
            get {
                return ResourceManager.GetString("ModificarPlanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 477.
        /// </summary>
        internal static string ModificarPlantilla {
            get {
                return ResourceManager.GetString("ModificarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 260.
        /// </summary>
        internal static string ModificarProfesion {
            get {
                return ResourceManager.GetString("ModificarProfesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 270.
        /// </summary>
        internal static string ModificarRegistreos {
            get {
                return ResourceManager.GetString("ModificarRegistreos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 146.
        /// </summary>
        internal static string ModificarResponsableFiscal {
            get {
                return ResourceManager.GetString("ModificarResponsableFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 171.
        /// </summary>
        internal static string ModificarSuperficie {
            get {
                return ResourceManager.GetString("ModificarSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 25.
        /// </summary>
        internal static string ModificarSuperficies {
            get {
                return ResourceManager.GetString("ModificarSuperficies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 623.
        /// </summary>
        internal static string ModificarSuperficieVigencia {
            get {
                return ResourceManager.GetString("ModificarSuperficieVigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 53.
        /// </summary>
        internal static string ModificarTablasAux {
            get {
                return ResourceManager.GetString("ModificarTablasAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 156.
        /// </summary>
        internal static string ModificarTitular {
            get {
                return ResourceManager.GetString("ModificarTitular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 219.
        /// </summary>
        internal static string ModificarTramites {
            get {
                return ResourceManager.GetString("ModificarTramites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 37.
        /// </summary>
        internal static string ModificarUsuarios {
            get {
                return ResourceManager.GetString("ModificarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 32.
        /// </summary>
        internal static string ModuloSeguridad {
            get {
                return ResourceManager.GetString("ModuloSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 520.
        /// </summary>
        internal static string MPAltaParcelasOrigen {
            get {
                return ResourceManager.GetString("MPAltaParcelasOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 521.
        /// </summary>
        internal static string MPBajaParcelasOrigen {
            get {
                return ResourceManager.GetString("MPBajaParcelasOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 522.
        /// </summary>
        internal static string MPModificacionParcelasOrigen {
            get {
                return ResourceManager.GetString("MPModificacionParcelasOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3.
        /// </summary>
        internal static string ObrasParticulares {
            get {
                return ResourceManager.GetString("ObrasParticulares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1001.
        /// </summary>
        internal static string PadronMunicipal {
            get {
                return ResourceManager.GetString("PadronMunicipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 619.
        /// </summary>
        internal static string PermiteDDJJSoRNoVigentes {
            get {
                return ResourceManager.GetString("PermiteDDJJSoRNoVigentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 192.
        /// </summary>
        internal static string Planeamiento {
            get {
                return ResourceManager.GetString("Planeamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 221.
        /// </summary>
        internal static string Planificarinspecciones {
            get {
                return ResourceManager.GetString("Planificarinspecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 165.
        /// </summary>
        internal static string PrimarioUbicacionObra {
            get {
                return ResourceManager.GetString("PrimarioUbicacionObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 350.
        /// </summary>
        internal static string PublicarDespublicarBibliotecaBA {
            get {
                return ResourceManager.GetString("PublicarDespublicarBibliotecaBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 349.
        /// </summary>
        internal static string PublicarDespublicarBibliotecaMT {
            get {
                return ResourceManager.GetString("PublicarDespublicarBibliotecaMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 475.
        /// </summary>
        internal static string PublicarPlantilla {
            get {
                return ResourceManager.GetString("PublicarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 264.
        /// </summary>
        internal static string QuitarDocumentos {
            get {
                return ResourceManager.GetString("QuitarDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 277.
        /// </summary>
        internal static string Rankingdetareasporusuarios {
            get {
                return ResourceManager.GetString("Rankingdetareasporusuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 279.
        /// </summary>
        internal static string RankingdeUusariosportareas {
            get {
                return ResourceManager.GetString("RankingdeUusariosportareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 280.
        /// </summary>
        internal static string RankingGeneraldetareas {
            get {
                return ResourceManager.GetString("RankingGeneraldetareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 103.
        /// </summary>
        internal static string RankingGeneraldetiposdeobjetosyCantidad {
            get {
                return ResourceManager.GetString("RankingGeneraldetiposdeobjetosyCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 127.
        /// </summary>
        internal static string RealizarAsosicion {
            get {
                return ResourceManager.GetString("RealizarAsosicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 128.
        /// </summary>
        internal static string RealizarDesasociacion {
            get {
                return ResourceManager.GetString("RealizarDesasociacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 518.
        /// </summary>
        internal static string ReasignacionTramites {
            get {
                return ResourceManager.GetString("ReasignacionTramites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 223.
        /// </summary>
        internal static string RegistrodeInspectores {
            get {
                return ResourceManager.GetString("RegistrodeInspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 337.
        /// </summary>
        internal static string Rentas {
            get {
                return ResourceManager.GetString("Rentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 222.
        /// </summary>
        internal static string TablerodeInspecciones {
            get {
                return ResourceManager.GetString("TablerodeInspecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 207.
        /// </summary>
        internal static string Valuacion {
            get {
                return ResourceManager.GetString("Valuacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 331.
        /// </summary>
        internal static string ValuacionIndividual {
            get {
                return ResourceManager.GetString("ValuacionIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 332.
        /// </summary>
        internal static string ValuacionMasiva {
            get {
                return ResourceManager.GetString("ValuacionMasiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1000.
        /// </summary>
        internal static string VIR {
            get {
                return ResourceManager.GetString("VIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 268.
        /// </summary>
        internal static string VisaulizarRegistros {
            get {
                return ResourceManager.GetString("VisaulizarRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 618.
        /// </summary>
        internal static string VisualizacionDDJJ {
            get {
                return ResourceManager.GetString("VisualizacionDDJJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 323.
        /// </summary>
        internal static string VisualizarABMExpedienteObra {
            get {
                return ResourceManager.GetString("VisualizarABMExpedienteObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 238.
        /// </summary>
        internal static string VisualizarActas {
            get {
                return ResourceManager.GetString("VisualizarActas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 212.
        /// </summary>
        internal static string VisualizarCertificados {
            get {
                return ResourceManager.GetString("VisualizarCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 500.
        /// </summary>
        internal static string VisualizarDesignaciones {
            get {
                return ResourceManager.GetString("VisualizarDesignaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 263.
        /// </summary>
        internal static string VisualizarDocumentos {
            get {
                return ResourceManager.GetString("VisualizarDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 251.
        /// </summary>
        internal static string VisualizarDomicilio {
            get {
                return ResourceManager.GetString("VisualizarDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 8.
        /// </summary>
        internal static string VisualizarExpedienteObra {
            get {
                return ResourceManager.GetString("VisualizarExpedienteObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 31.
        /// </summary>
        internal static string VisualizarInformeEstadistico {
            get {
                return ResourceManager.GetString("VisualizarInformeEstadistico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 29.
        /// </summary>
        internal static string VisualizarInformeSeguimiento {
            get {
                return ResourceManager.GetString("VisualizarInformeSeguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 226.
        /// </summary>
        internal static string VisualizarInspeccion {
            get {
                return ResourceManager.GetString("VisualizarInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 230.
        /// </summary>
        internal static string Visualizarinspectores {
            get {
                return ResourceManager.GetString("Visualizarinspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 16.
        /// </summary>
        internal static string VisualizarLiquidaciones {
            get {
                return ResourceManager.GetString("VisualizarLiquidaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 318.
        /// </summary>
        internal static string VisualizarMantenedor {
            get {
                return ResourceManager.GetString("VisualizarMantenedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 23.
        /// </summary>
        internal static string VisualizarObservaciones {
            get {
                return ResourceManager.GetString("VisualizarObservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 245.
        /// </summary>
        internal static string Visualizarpersona {
            get {
                return ResourceManager.GetString("Visualizarpersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 12.
        /// </summary>
        internal static string VisualizarPlanos {
            get {
                return ResourceManager.GetString("VisualizarPlanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 258.
        /// </summary>
        internal static string VisualizarProfesion {
            get {
                return ResourceManager.GetString("VisualizarProfesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 27.
        /// </summary>
        internal static string VisualizarSuperficies {
            get {
                return ResourceManager.GetString("VisualizarSuperficies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 217.
        /// </summary>
        internal static string VisualizarTramites {
            get {
                return ResourceManager.GetString("VisualizarTramites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 319.
        /// </summary>
        internal static string VisualizarValuacion {
            get {
                return ResourceManager.GetString("VisualizarValuacion", resourceCulture);
            }
        }
    }
}
