-- Interfase DGCeIT
INSERT INTO GE_PARAMETRO (ID_PARAMETRO, DESCRIPCION, VALOR, AGRUPADOR, CLAVE)
SELECT MAX(ID_PARAMETRO) + 1, 'URL del Webservice Externo de la DGCeIT',
    'http://localhost:3171/DGCeITService.asmx', 
    'INTERFASE_DGC', 'IDGC_EXT_SERVICE_URL'  
FROM GE_PARAMETRO;

-- Interfase DGCeIT
INSERT INTO GE_PARAMETRO (ID_PARAMETRO, DESCRIPCION, VALOR, AGRUPADOR, CLAVE)
SELECT MAX(ID_PARAMETRO) + 1, 'Layers publicados por la DGCeIT',
    'DEPARTAMENTOS,EJIDOS,DIVISIONES,PARCELA_URBANA,PARCELA_RURAL', 
    'INTERFASE_DGC', 'IDGC_LAYERS_DGC'  
FROM GE_PARAMETRO;

COMMIT;