//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GeoSit.Web.Api.inmAvaluo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Avaluo de InmuebleBinding", Namespace="urn:inmAvaluo")]
    public partial class AvaluodeInmueble : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback avaluoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AvaluodeInmueble() {
            this.Url = global::GeoSit.Web.Api.Properties.Settings.Default.GeoSit_Web_Api_inmAvaluo_Avaluo_de_Inmueble;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event avaluoCompletedEventHandler avaluoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:inmuebles#avaluo", RequestNamespace="urn:inmAvaluo", ResponseNamespace="urn:inmAvaluo")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string avaluo(datos_inmueble datos_inmueble) {
            object[] results = this.Invoke("avaluo", new object[] {
                        datos_inmueble});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void avaluoAsync(datos_inmueble datos_inmueble) {
            this.avaluoAsync(datos_inmueble, null);
        }
        
        /// <remarks/>
        public void avaluoAsync(datos_inmueble datos_inmueble, object userState) {
            if ((this.avaluoOperationCompleted == null)) {
                this.avaluoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnavaluoOperationCompleted);
            }
            this.InvokeAsync("avaluo", new object[] {
                        datos_inmueble}, this.avaluoOperationCompleted, userState);
        }
        
        private void OnavaluoOperationCompleted(object arg) {
            if ((this.avaluoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.avaluoCompleted(this, new avaluoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:inmAvaluo")]
    public partial class datos_inmueble {
        
        private int obj_idField;
        
        private string suptField;
        
        private string supmField;
        
        private string avaltField;
        
        private string avalmField;
        
        private string frenteField;
        
        private int regimenField;
        
        private int es_esquinaField;
        
        private int es_calleppalField;
        
        private string zonatField;
        
        private int zonavField;
        
        private int zonaopField;
        
        private int aguaField;
        
        private int cloacaField;
        
        private int gasField;
        
        private int alumField;
        
        private int pavField;
        
        private int vigenciaField;
        
        /// <remarks/>
        public int obj_id {
            get {
                return this.obj_idField;
            }
            set {
                this.obj_idField = value;
            }
        }
        
        /// <remarks/>
        public string supt {
            get {
                return this.suptField;
            }
            set {
                this.suptField = value;
            }
        }
        
        /// <remarks/>
        public string supm {
            get {
                return this.supmField;
            }
            set {
                this.supmField = value;
            }
        }
        
        /// <remarks/>
        public string avalt {
            get {
                return this.avaltField;
            }
            set {
                this.avaltField = value;
            }
        }
        
        /// <remarks/>
        public string avalm {
            get {
                return this.avalmField;
            }
            set {
                this.avalmField = value;
            }
        }
        
        /// <remarks/>
        public string frente {
            get {
                return this.frenteField;
            }
            set {
                this.frenteField = value;
            }
        }
        
        /// <remarks/>
        public int regimen {
            get {
                return this.regimenField;
            }
            set {
                this.regimenField = value;
            }
        }
        
        /// <remarks/>
        public int es_esquina {
            get {
                return this.es_esquinaField;
            }
            set {
                this.es_esquinaField = value;
            }
        }
        
        /// <remarks/>
        public int es_calleppal {
            get {
                return this.es_calleppalField;
            }
            set {
                this.es_calleppalField = value;
            }
        }
        
        /// <remarks/>
        public string zonat {
            get {
                return this.zonatField;
            }
            set {
                this.zonatField = value;
            }
        }
        
        /// <remarks/>
        public int zonav {
            get {
                return this.zonavField;
            }
            set {
                this.zonavField = value;
            }
        }
        
        /// <remarks/>
        public int zonaop {
            get {
                return this.zonaopField;
            }
            set {
                this.zonaopField = value;
            }
        }
        
        /// <remarks/>
        public int agua {
            get {
                return this.aguaField;
            }
            set {
                this.aguaField = value;
            }
        }
        
        /// <remarks/>
        public int cloaca {
            get {
                return this.cloacaField;
            }
            set {
                this.cloacaField = value;
            }
        }
        
        /// <remarks/>
        public int gas {
            get {
                return this.gasField;
            }
            set {
                this.gasField = value;
            }
        }
        
        /// <remarks/>
        public int alum {
            get {
                return this.alumField;
            }
            set {
                this.alumField = value;
            }
        }
        
        /// <remarks/>
        public int pav {
            get {
                return this.pavField;
            }
            set {
                this.pavField = value;
            }
        }
        
        /// <remarks/>
        public int vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void avaluoCompletedEventHandler(object sender, avaluoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class avaluoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal avaluoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591