-- Interfase DGCeIT
INSERT INTO GE_PARAMETRO (ID_PARAMETRO, DESCRIPCION, VALOR, AGRUPADOR, CLAVE)
SELECT MAX(ID_PARAMETRO) + 1, 'URL de la Aplicación Web de la DGCeIT',
    'http://localhost:39700', 'INTERFASE_DGC', 'IDGC_MAIN_WEB_URL'  
FROM GE_PARAMETRO;

INSERT INTO GE_PARAMETRO (ID_PARAMETRO, DESCRIPCION, VALOR, AGRUPADOR, CLAVE)
SELECT MAX(ID_PARAMETRO) + 1, 'GUID del Servicio de Reportes de la DGCeIT', 
    '{7FAEA6AB-0E81-435c-BF07-019408AE9833}', 'INTERFASE_DGC', 'IDGC_REPORTS_SERVICE_GUID'  
FROM GE_PARAMETRO;

INSERT INTO GE_PARAMETRO (ID_PARAMETRO, DESCRIPCION, VALOR, AGRUPADOR, CLAVE)
SELECT MAX(ID_PARAMETRO) + 1, 'Layers aplicables al Reporte General del Inmueble', 
    'PARCELA_URBANA', 'INTERFASE_DGC', 'IDGC_LAYERS_REPORTE_GENERAL_INMUEBLE'  
FROM GE_PARAMETRO;

INSERT INTO GE_PARAMETRO (ID_PARAMETRO, DESCRIPCION, VALOR, AGRUPADOR, CLAVE)
SELECT MAX(ID_PARAMETRO) + 1, 'Layers aplicables a la Copia de Parcelas', 
    'PARCELA_URBANA', 'INTERFASE_DGC', 'IDGC_LAYERS_COPIA_PARCELAS'  
FROM GE_PARAMETRO;

-- Interfase Sistema Tributario
INSERT INTO GE_PARAMETRO (ID_PARAMETRO, DESCRIPCION, VALOR, AGRUPADOR, CLAVE)
SELECT MAX(ID_PARAMETRO) + 1, 'Webservice de Búsqueda de Personas del Sistema Tributario', 
    'http://emaw70512.hopto.org/samws/clientes/clientePersonas.php', 
    'INTERFASE_SISTEMA_TRIBUTARIO', 'IST_WS_BUSQUEDA_PERSONAS'  
FROM GE_PARAMETRO;

COMMIT;