//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoSit.Data.BusinessEntities.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Eventos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Eventos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoSit.Data.BusinessEntities.GlobalResources.Eventos", typeof(Eventos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 162.
        /// </summary>
        public static string AbrirLibroDiario {
            get {
                return ResourceManager.GetString("AbrirLibroDiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 233.
        /// </summary>
        public static string ActualizarInforme {
            get {
                return ResourceManager.GetString("ActualizarInforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        public static string AgregarFeriados {
            get {
                return ResourceManager.GetString("AgregarFeriados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        public static string AgregarHorarios {
            get {
                return ResourceManager.GetString("AgregarHorarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 137.
        /// </summary>
        public static string AgregarObjetosColeccion {
            get {
                return ResourceManager.GetString("AgregarObjetosColeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        public static string AgregarPerfiles {
            get {
                return ResourceManager.GetString("AgregarPerfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string AgregarPlano {
            get {
                return ResourceManager.GetString("AgregarPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string AgregarPlanos {
            get {
                return ResourceManager.GetString("AgregarPlanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64.
        /// </summary>
        public static string AgregarRegistro {
            get {
                return ResourceManager.GetString("AgregarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 155.
        /// </summary>
        public static string AgregarRemito {
            get {
                return ResourceManager.GetString("AgregarRemito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        public static string AgregarTablasAux {
            get {
                return ResourceManager.GetString("AgregarTablasAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string AgregarUsuarios {
            get {
                return ResourceManager.GetString("AgregarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string AltaAlfanumericodeParcelasyPosesiones {
            get {
                return ResourceManager.GetString("AltaAlfanumericodeParcelasyPosesiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 85.
        /// </summary>
        public static string AltaAtributo {
            get {
                return ResourceManager.GetString("AltaAtributo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 118.
        /// </summary>
        public static string AltaAtributoZona {
            get {
                return ResourceManager.GetString("AltaAtributoZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 91.
        /// </summary>
        public static string AltaCertificados {
            get {
                return ResourceManager.GetString("AltaCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 138.
        /// </summary>
        public static string AltaColeccion {
            get {
                return ResourceManager.GetString("AltaColeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 78.
        /// </summary>
        public static string AltaControlTecnico {
            get {
                return ResourceManager.GetString("AltaControlTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 199.
        /// </summary>
        public static string AltaDDJJE1 {
            get {
                return ResourceManager.GetString("AltaDDJJE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string AltaDDJJE2 {
            get {
                return ResourceManager.GetString("AltaDDJJE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 198.
        /// </summary>
        public static string AltaDDJJSoR {
            get {
                return ResourceManager.GetString("AltaDDJJSoR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 197.
        /// </summary>
        public static string AltaDDJJU {
            get {
                return ResourceManager.GetString("AltaDDJJU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 103.
        /// </summary>
        public static string AltadeActas {
            get {
                return ResourceManager.GetString("AltadeActas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 97.
        /// </summary>
        public static string AltadeInspeccion {
            get {
                return ResourceManager.GetString("AltadeInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string Altadeinspectores {
            get {
                return ResourceManager.GetString("Altadeinspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 188.
        /// </summary>
        public static string AltaDeMensura {
            get {
                return ResourceManager.GetString("AltaDeMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 191.
        /// </summary>
        public static string AltaDeParcelaMensura {
            get {
                return ResourceManager.GetString("AltaDeParcelaMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        public static string AltadeParcelasDestino {
            get {
                return ResourceManager.GetString("AltadeParcelasDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string AltadeParcelasOrigen {
            get {
                return ResourceManager.GetString("AltadeParcelasOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 106.
        /// </summary>
        public static string AltadePersonas {
            get {
                return ResourceManager.GetString("AltadePersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 139.
        /// </summary>
        public static string AltaDePlantilla {
            get {
                return ResourceManager.GetString("AltaDePlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 109.
        /// </summary>
        public static string AltadeProfesion {
            get {
                return ResourceManager.GetString("AltadeProfesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 112.
        /// </summary>
        public static string Altaderegistros {
            get {
                return ResourceManager.GetString("Altaderegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 88.
        /// </summary>
        public static string AltadeResultadodeBusqueda {
            get {
                return ResourceManager.GetString("AltadeResultadodeBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 194.
        /// </summary>
        public static string AltaDesignacion {
            get {
                return ResourceManager.GetString("AltaDesignacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 94.
        /// </summary>
        public static string AltadeTramites {
            get {
                return ResourceManager.GetString("AltadeTramites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 68.
        /// </summary>
        public static string AltaDocumento {
            get {
                return ResourceManager.GetString("AltaDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38.
        /// </summary>
        public static string AltaDocumentosParcela {
            get {
                return ResourceManager.GetString("AltaDocumentosParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 47.
        /// </summary>
        public static string AltaDocumentosUnidadTributaria {
            get {
                return ResourceManager.GetString("AltaDocumentosUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41.
        /// </summary>
        public static string AltaDomicilio {
            get {
                return ResourceManager.GetString("AltaDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        public static string AltaDominio {
            get {
                return ResourceManager.GetString("AltaDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 63.
        /// </summary>
        public static string AltaEstado {
            get {
                return ResourceManager.GetString("AltaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 56.
        /// </summary>
        public static string AltaExpedientesObra {
            get {
                return ResourceManager.GetString("AltaExpedientesObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 77.
        /// </summary>
        public static string AltaInspeccion {
            get {
                return ResourceManager.GetString("AltaInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 74.
        /// </summary>
        public static string AltaLiquidacion {
            get {
                return ResourceManager.GetString("AltaLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        public static string AltaMantenedorUnidadTributaria {
            get {
                return ResourceManager.GetString("AltaMantenedorUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        public static string AltaNomenclatura {
            get {
                return ResourceManager.GetString("AltaNomenclatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 124.
        /// </summary>
        public static string AltaObjetoAdministrativo {
            get {
                return ResourceManager.GetString("AltaObjetoAdministrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 115.
        /// </summary>
        public static string AltaObjetoInf {
            get {
                return ResourceManager.GetString("AltaObjetoInf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 81.
        /// </summary>
        public static string AltaObservacion {
            get {
                return ResourceManager.GetString("AltaObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 134.
        /// </summary>
        public static string AltaParcela {
            get {
                return ResourceManager.GetString("AltaParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 121.
        /// </summary>
        public static string AltaParcelagrafica {
            get {
                return ResourceManager.GetString("AltaParcelagrafica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 209.
        /// </summary>
        public static string AltaParcelaOrigen {
            get {
                return ResourceManager.GetString("AltaParcelaOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 71.
        /// </summary>
        public static string AltaPersona {
            get {
                return ResourceManager.GetString("AltaPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44.
        /// </summary>
        public static string AltaResponsableFiscal {
            get {
                return ResourceManager.GetString("AltaResponsableFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65.
        /// </summary>
        public static string AltaSuperficie {
            get {
                return ResourceManager.GetString("AltaSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 53.
        /// </summary>
        public static string AltaTitular {
            get {
                return ResourceManager.GetString("AltaTitular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 61.
        /// </summary>
        public static string AltaUbicacionObra {
            get {
                return ResourceManager.GetString("AltaUbicacionObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 59.
        /// </summary>
        public static string AltaUnidadesTributarias {
            get {
                return ResourceManager.GetString("AltaUnidadesTributarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127.
        /// </summary>
        public static string AltaValuacion {
            get {
                return ResourceManager.GetString("AltaValuacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 131.
        /// </summary>
        public static string AltaValuacionDetalle {
            get {
                return ResourceManager.GetString("AltaValuacionDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 165.
        /// </summary>
        public static string AnexarInforme {
            get {
                return ResourceManager.GetString("AnexarInforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 232.
        /// </summary>
        public static string AnexarInformeFirmado {
            get {
                return ResourceManager.GetString("AnexarInformeFirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 140.
        /// </summary>
        public static string AnularCapaLibroTramite {
            get {
                return ResourceManager.GetString("AnularCapaLibroTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 147.
        /// </summary>
        public static string AnularDerivaciónTramite {
            get {
                return ResourceManager.GetString("AnularDerivaciónTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 143.
        /// </summary>
        public static string AnularTramite {
            get {
                return ResourceManager.GetString("AnularTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 230.
        /// </summary>
        public static string AprobarTramite {
            get {
                return ResourceManager.GetString("AprobarTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 145.
        /// </summary>
        public static string ArchivarTramtie {
            get {
                return ResourceManager.GetString("ArchivarTramtie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 119.
        /// </summary>
        public static string BajaAtributoZona {
            get {
                return ResourceManager.GetString("BajaAtributoZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 93.
        /// </summary>
        public static string BajaCertificados {
            get {
                return ResourceManager.GetString("BajaCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 140.
        /// </summary>
        public static string BajaColeccion {
            get {
                return ResourceManager.GetString("BajaColeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 79.
        /// </summary>
        public static string BajaControlTecnico {
            get {
                return ResourceManager.GetString("BajaControlTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 213.
        /// </summary>
        public static string BajaDDJJ {
            get {
                return ResourceManager.GetString("BajaDDJJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 105.
        /// </summary>
        public static string Bajadeactas {
            get {
                return ResourceManager.GetString("Bajadeactas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 87.
        /// </summary>
        public static string BajadeAtributos {
            get {
                return ResourceManager.GetString("BajadeAtributos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99.
        /// </summary>
        public static string BajadeInspeccion {
            get {
                return ResourceManager.GetString("BajadeInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101.
        /// </summary>
        public static string Bajadeinspectores {
            get {
                return ResourceManager.GetString("Bajadeinspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 73.
        /// </summary>
        public static string BajadeLiquidacion {
            get {
                return ResourceManager.GetString("BajadeLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33.
        /// </summary>
        public static string BajadeParcelasDestino {
            get {
                return ResourceManager.GetString("BajadeParcelasDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.
        /// </summary>
        public static string BajadeParcelasOrigen {
            get {
                return ResourceManager.GetString("BajadeParcelasOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 108.
        /// </summary>
        public static string BajadePersonas {
            get {
                return ResourceManager.GetString("BajadePersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 141.
        /// </summary>
        public static string BajaDePlantilla {
            get {
                return ResourceManager.GetString("BajaDePlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 111.
        /// </summary>
        public static string BajadeProfesion {
            get {
                return ResourceManager.GetString("BajadeProfesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 114.
        /// </summary>
        public static string BajadeRegistros {
            get {
                return ResourceManager.GetString("BajadeRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90.
        /// </summary>
        public static string BajadeResultadodeBusqueda {
            get {
                return ResourceManager.GetString("BajadeResultadodeBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 195.
        /// </summary>
        public static string BajaDesignacion {
            get {
                return ResourceManager.GetString("BajaDesignacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96.
        /// </summary>
        public static string BajadeTramite {
            get {
                return ResourceManager.GetString("BajadeTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 69.
        /// </summary>
        public static string BajaDocumento {
            get {
                return ResourceManager.GetString("BajaDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.
        /// </summary>
        public static string BajaDocumentosParcela {
            get {
                return ResourceManager.GetString("BajaDocumentosParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49.
        /// </summary>
        public static string BajaDocumentosUnidadTributaria {
            get {
                return ResourceManager.GetString("BajaDocumentosUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 43.
        /// </summary>
        public static string BajaDomicilio {
            get {
                return ResourceManager.GetString("BajaDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52.
        /// </summary>
        public static string BajaDominio {
            get {
                return ResourceManager.GetString("BajaDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 84.
        /// </summary>
        public static string BajaExpedientedeObra {
            get {
                return ResourceManager.GetString("BajaExpedientedeObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 57.
        /// </summary>
        public static string BajaExpedientesObra {
            get {
                return ResourceManager.GetString("BajaExpedientesObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75.
        /// </summary>
        public static string BajaLiquidacion {
            get {
                return ResourceManager.GetString("BajaLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        public static string BajaMantenedorUnidadTributaria {
            get {
                return ResourceManager.GetString("BajaMantenedorUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37.
        /// </summary>
        public static string BajaNomenclatura {
            get {
                return ResourceManager.GetString("BajaNomenclatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 125.
        /// </summary>
        public static string BajaObjetoAdministrativo {
            get {
                return ResourceManager.GetString("BajaObjetoAdministrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 116.
        /// </summary>
        public static string BajaObjetoInf {
            get {
                return ResourceManager.GetString("BajaObjetoInf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 82.
        /// </summary>
        public static string BajaObservacion {
            get {
                return ResourceManager.GetString("BajaObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 136.
        /// </summary>
        public static string BajaParcela {
            get {
                return ResourceManager.GetString("BajaParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123.
        /// </summary>
        public static string BajaParcelagrafica {
            get {
                return ResourceManager.GetString("BajaParcelagrafica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 210.
        /// </summary>
        public static string BajaParcelaOrigen {
            get {
                return ResourceManager.GetString("BajaParcelaOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 72.
        /// </summary>
        public static string BajaPersona {
            get {
                return ResourceManager.GetString("BajaPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 46.
        /// </summary>
        public static string BajaResponsableFiscal {
            get {
                return ResourceManager.GetString("BajaResponsableFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 66.
        /// </summary>
        public static string BajaSuperficie {
            get {
                return ResourceManager.GetString("BajaSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55.
        /// </summary>
        public static string BajaTitular {
            get {
                return ResourceManager.GetString("BajaTitular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 62.
        /// </summary>
        public static string BajaUbicacionObra {
            get {
                return ResourceManager.GetString("BajaUbicacionObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.
        /// </summary>
        public static string BajaUnidadesTributarias {
            get {
                return ResourceManager.GetString("BajaUnidadesTributarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 129.
        /// </summary>
        public static string BajaValuacion {
            get {
                return ResourceManager.GetString("BajaValuacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 133.
        /// </summary>
        public static string BajaValuacionDetalle {
            get {
                return ResourceManager.GetString("BajaValuacionDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 163.
        /// </summary>
        public static string CerrarLibroDiario {
            get {
                return ResourceManager.GetString("CerrarLibroDiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 137.
        /// </summary>
        public static string DerivarTramite {
            get {
                return ResourceManager.GetString("DerivarTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 148.
        /// </summary>
        public static string DesarchivarTramite {
            get {
                return ResourceManager.GetString("DesarchivarTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 144.
        /// </summary>
        public static string DespacharTramite {
            get {
                return ResourceManager.GetString("DespacharTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 156.
        /// </summary>
        public static string DespublicarBibliotecaBA {
            get {
                return ResourceManager.GetString("DespublicarBibliotecaBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 142.
        /// </summary>
        public static string DespublicarBibliotecaMT {
            get {
                return ResourceManager.GetString("DespublicarBibliotecaMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150.
        /// </summary>
        public static string EditarTramite {
            get {
                return ResourceManager.GetString("EditarTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 158.
        /// </summary>
        public static string EliminarBibliotecaBA {
            get {
                return ResourceManager.GetString("EliminarBibliotecaBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 143.
        /// </summary>
        public static string EliminarBibliotecaMT {
            get {
                return ResourceManager.GetString("EliminarBibliotecaMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        public static string EliminarFeriados {
            get {
                return ResourceManager.GetString("EliminarFeriados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        public static string EliminarHorarios {
            get {
                return ResourceManager.GetString("EliminarHorarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.
        /// </summary>
        public static string EliminarInspectores {
            get {
                return ResourceManager.GetString("EliminarInspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 190.
        /// </summary>
        public static string EliminarMensura {
            get {
                return ResourceManager.GetString("EliminarMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 144.
        /// </summary>
        public static string EliminarObjetosColeccion {
            get {
                return ResourceManager.GetString("EliminarObjetosColeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        public static string EliminarParcelaDestino {
            get {
                return ResourceManager.GetString("EliminarParcelaDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        public static string EliminarParcelaOrigen {
            get {
                return ResourceManager.GetString("EliminarParcelaOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        public static string EliminarPerfiles {
            get {
                return ResourceManager.GetString("EliminarPerfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 66.
        /// </summary>
        public static string EliminarRegistro {
            get {
                return ResourceManager.GetString("EliminarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        public static string EliminarTablaAux {
            get {
                return ResourceManager.GetString("EliminarTablaAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string EliminarUsuarios {
            get {
                return ResourceManager.GetString("EliminarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36.
        /// </summary>
        public static string ExistenciaDeCorteAnterior {
            get {
                return ResourceManager.GetString("ExistenciaDeCorteAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string Exportar {
            get {
                return ResourceManager.GetString("Exportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 145.
        /// </summary>
        public static string ExportarColeccion {
            get {
                return ResourceManager.GetString("ExportarColeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 159.
        /// </summary>
        public static string ExportarExcelBA {
            get {
                return ResourceManager.GetString("ExportarExcelBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49.
        /// </summary>
        public static string ExportarExcelMT {
            get {
                return ResourceManager.GetString("ExportarExcelMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 142.
        /// </summary>
        public static string FinalizarTramite {
            get {
                return ResourceManager.GetString("FinalizarTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 146.
        /// </summary>
        public static string GeneracionPloteoGeneral {
            get {
                return ResourceManager.GetString("GeneracionPloteoGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 146.
        /// </summary>
        public static string GeneracionPloteoPlanchetaA4 {
            get {
                return ResourceManager.GetString("GeneracionPloteoPlanchetaA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 155.
        /// </summary>
        public static string GeneracionResultadosEnBA {
            get {
                return ResourceManager.GetString("GeneracionResultadosEnBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 146.
        /// </summary>
        public static string GeneracionResultadosEnMT {
            get {
                return ResourceManager.GetString("GeneracionResultadosEnMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 214.
        /// </summary>
        public static string GenerarCertificadoValuatorio {
            get {
                return ResourceManager.GetString("GenerarCertificadoValuatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 215.
        /// </summary>
        public static string GenerarInformeCatastral {
            get {
                return ResourceManager.GetString("GenerarInformeCatastral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 217.
        /// </summary>
        public static string GenerarInformeHistoricoTitulares {
            get {
                return ResourceManager.GetString("GenerarInformeHistoricoTitulares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 220.
        /// </summary>
        public static string GenerarInformeHistoricoValuaciones {
            get {
                return ResourceManager.GetString("GenerarInformeHistoricoValuaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 216.
        /// </summary>
        public static string GenerarInformeParcelario {
            get {
                return ResourceManager.GetString("GenerarInformeParcelario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 219.
        /// </summary>
        public static string GenerarInformePropiedad {
            get {
                return ResourceManager.GetString("GenerarInformePropiedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 221.
        /// </summary>
        public static string GenerarInformeSituacion {
            get {
                return ResourceManager.GetString("GenerarInformeSituacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 218.
        /// </summary>
        public static string GenerarInformeUT {
            get {
                return ResourceManager.GetString("GenerarInformeUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 147.
        /// </summary>
        public static string GenerarPdf {
            get {
                return ResourceManager.GetString("GenerarPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 148.
        /// </summary>
        public static string GrabarBibliotecaMT {
            get {
                return ResourceManager.GetString("GrabarBibliotecaMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 160.
        /// </summary>
        public static string GrabarColeccionBA {
            get {
                return ResourceManager.GetString("GrabarColeccionBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 149.
        /// </summary>
        public static string GrabarColeccionMT {
            get {
                return ResourceManager.GetString("GrabarColeccionMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string GuardarExpedienteObra {
            get {
                return ResourceManager.GetString("GuardarExpedienteObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string ImportarArchivo {
            get {
                return ResourceManager.GetString("ImportarArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150.
        /// </summary>
        public static string ImportarColeccion {
            get {
                return ResourceManager.GetString("ImportarColeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 139.
        /// </summary>
        public static string IngresarTramite {
            get {
                return ResourceManager.GetString("IngresarTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34.
        /// </summary>
        public static string MedidoresDiferenciadosPorMarca {
            get {
                return ResourceManager.GetString("MedidoresDiferenciadosPorMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120.
        /// </summary>
        public static string ModificacionAtributoZona {
            get {
                return ResourceManager.GetString("ModificacionAtributoZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104.
        /// </summary>
        public static string ModificaciondeActas {
            get {
                return ResourceManager.GetString("ModificaciondeActas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 86.
        /// </summary>
        public static string ModificaciondeAtributos {
            get {
                return ResourceManager.GetString("ModificaciondeAtributos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 189.
        /// </summary>
        public static string ModificacionDeMensura {
            get {
                return ResourceManager.GetString("ModificacionDeMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 151.
        /// </summary>
        public static string ModificacionDePlantilla {
            get {
                return ResourceManager.GetString("ModificacionDePlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 89.
        /// </summary>
        public static string ModificaciondeResultadodeBusqueda {
            get {
                return ResourceManager.GetString("ModificaciondeResultadodeBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58.
        /// </summary>
        public static string ModificacionExpedientesObra {
            get {
                return ResourceManager.GetString("ModificacionExpedientesObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 126.
        /// </summary>
        public static string ModificacionObjetoAdministrativo {
            get {
                return ResourceManager.GetString("ModificacionObjetoAdministrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 117.
        /// </summary>
        public static string ModificacionObjetoInf {
            get {
                return ResourceManager.GetString("ModificacionObjetoInf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 122.
        /// </summary>
        public static string ModificacionParcelaGrafica {
            get {
                return ResourceManager.GetString("ModificacionParcelaGrafica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 211.
        /// </summary>
        public static string ModificacionParcelaOrigen {
            get {
                return ResourceManager.GetString("ModificacionParcelaOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128.
        /// </summary>
        public static string ModificacionValuacion {
            get {
                return ResourceManager.GetString("ModificacionValuacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 132.
        /// </summary>
        public static string ModificacionValuacionDetalle {
            get {
                return ResourceManager.GetString("ModificacionValuacionDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 212.
        /// </summary>
        public static string ModificacionVIR {
            get {
                return ResourceManager.GetString("ModificacionVIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 92.
        /// </summary>
        public static string ModificarCertificados {
            get {
                return ResourceManager.GetString("ModificarCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 152.
        /// </summary>
        public static string ModificarColeccion {
            get {
                return ResourceManager.GetString("ModificarColeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80.
        /// </summary>
        public static string ModificarControlTecnico {
            get {
                return ResourceManager.GetString("ModificarControlTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 203.
        /// </summary>
        public static string ModificarDDJJE1 {
            get {
                return ResourceManager.GetString("ModificarDDJJE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 204.
        /// </summary>
        public static string ModificarDDJJE2 {
            get {
                return ResourceManager.GetString("ModificarDDJJE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 202.
        /// </summary>
        public static string ModificarDDJJSoR {
            get {
                return ResourceManager.GetString("ModificarDDJJSoR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 201.
        /// </summary>
        public static string ModificarDDJJU {
            get {
                return ResourceManager.GetString("ModificarDDJJU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 196.
        /// </summary>
        public static string ModificarDesignacion {
            get {
                return ResourceManager.GetString("ModificarDesignacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70.
        /// </summary>
        public static string ModificarDocumento {
            get {
                return ResourceManager.GetString("ModificarDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 39.
        /// </summary>
        public static string ModificarDocumentosParcela {
            get {
                return ResourceManager.GetString("ModificarDocumentosParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48.
        /// </summary>
        public static string ModificarDocumentosUnidadTributaria {
            get {
                return ResourceManager.GetString("ModificarDocumentosUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42.
        /// </summary>
        public static string ModificarDomicilio {
            get {
                return ResourceManager.GetString("ModificarDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51.
        /// </summary>
        public static string ModificarDominio {
            get {
                return ResourceManager.GetString("ModificarDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64.
        /// </summary>
        public static string ModificarEstado {
            get {
                return ResourceManager.GetString("ModificarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        public static string ModificarFeriados {
            get {
                return ResourceManager.GetString("ModificarFeriados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string ModificarHorarios {
            get {
                return ResourceManager.GetString("ModificarHorarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 98.
        /// </summary>
        public static string ModificarInspeccion {
            get {
                return ResourceManager.GetString("ModificarInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 102.
        /// </summary>
        public static string Modificarinspectores {
            get {
                return ResourceManager.GetString("Modificarinspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 76.
        /// </summary>
        public static string ModificarLiquidacion {
            get {
                return ResourceManager.GetString("ModificarLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34.
        /// </summary>
        public static string ModificarMantenedorParcelario {
            get {
                return ResourceManager.GetString("ModificarMantenedorParcelario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string ModificarMantenedorUnidadTributaria {
            get {
                return ResourceManager.GetString("ModificarMantenedorUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36.
        /// </summary>
        public static string ModificarNomenclatura {
            get {
                return ResourceManager.GetString("ModificarNomenclatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 83.
        /// </summary>
        public static string ModificarObservacion {
            get {
                return ResourceManager.GetString("ModificarObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string ModificarParametrosGenerales {
            get {
                return ResourceManager.GetString("ModificarParametrosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 135.
        /// </summary>
        public static string ModificarParcela {
            get {
                return ResourceManager.GetString("ModificarParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string ModificarPerfiles {
            get {
                return ResourceManager.GetString("ModificarPerfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 107.
        /// </summary>
        public static string ModificarPersonas {
            get {
                return ResourceManager.GetString("ModificarPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 110.
        /// </summary>
        public static string ModificarProfesion {
            get {
                return ResourceManager.GetString("ModificarProfesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 113.
        /// </summary>
        public static string ModificarRegistreos {
            get {
                return ResourceManager.GetString("ModificarRegistreos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65.
        /// </summary>
        public static string ModificarRegistro {
            get {
                return ResourceManager.GetString("ModificarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45.
        /// </summary>
        public static string ModificarResponsableFiscal {
            get {
                return ResourceManager.GetString("ModificarResponsableFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 67.
        /// </summary>
        public static string ModificarSuperficie {
            get {
                return ResourceManager.GetString("ModificarSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        public static string ModificarTablasAux {
            get {
                return ResourceManager.GetString("ModificarTablasAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 54.
        /// </summary>
        public static string ModificarTitular {
            get {
                return ResourceManager.GetString("ModificarTitular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 95.
        /// </summary>
        public static string ModificarTramites {
            get {
                return ResourceManager.GetString("ModificarTramites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string ModificarUsuarios {
            get {
                return ResourceManager.GetString("ModificarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string NoAutorizado {
            get {
                return ResourceManager.GetString("NoAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 205.
        /// </summary>
        public static string NuevaValuacion {
            get {
                return ResourceManager.GetString("NuevaValuacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 222.
        /// </summary>
        public static string ObservarTramite {
            get {
                return ResourceManager.GetString("ObservarTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 206.
        /// </summary>
        public static string PresentarTramite {
            get {
                return ResourceManager.GetString("PresentarTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192.
        /// </summary>
        public static string ProcesarTramite {
            get {
                return ResourceManager.GetString("ProcesarTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 157.
        /// </summary>
        public static string PublicarBibliotecaBA {
            get {
                return ResourceManager.GetString("PublicarBibliotecaBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 153.
        /// </summary>
        public static string PublicarBibliotecaMT {
            get {
                return ResourceManager.GetString("PublicarBibliotecaMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37.
        /// </summary>
        public static string RangosDeConsumo {
            get {
                return ResourceManager.GetString("RangosDeConsumo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        public static string RankingAntiguedadEnDias {
            get {
                return ResourceManager.GetString("RankingAntiguedadEnDias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string RankingDeFacturasImpagas {
            get {
                return ResourceManager.GetString("RankingDeFacturasImpagas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.
        /// </summary>
        public static string RankingTotalDeDeuda {
            get {
                return ResourceManager.GetString("RankingTotalDeDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 223.
        /// </summary>
        public static string ReasignarTramite {
            get {
                return ResourceManager.GetString("ReasignarTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 141.
        /// </summary>
        public static string RechazarTramite {
            get {
                return ResourceManager.GetString("RechazarTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 146.
        /// </summary>
        public static string RecibirPresentadoTramite {
            get {
                return ResourceManager.GetString("RecibirPresentadoTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 138.
        /// </summary>
        public static string RecibirTramite {
            get {
                return ResourceManager.GetString("RecibirTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 149.
        /// </summary>
        public static string ReingresarTramite {
            get {
                return ResourceManager.GetString("ReingresarTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        public static string TiposDeCorte {
            get {
                return ResourceManager.GetString("TiposDeCorte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33.
        /// </summary>
        public static string TodosLosMedidores {
            get {
                return ResourceManager.GetString("TodosLosMedidores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 130.
        /// </summary>
        public static string ValuacionTemporal {
            get {
                return ResourceManager.GetString("ValuacionTemporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 161.
        /// </summary>
        public static string VerMapaBA {
            get {
                return ResourceManager.GetString("VerMapaBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 154.
        /// </summary>
        public static string VerMapaMT {
            get {
                return ResourceManager.GetString("VerMapaMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 229.
        /// </summary>
        public static string VisarCatastro {
            get {
                return ResourceManager.GetString("VisarCatastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 228.
        /// </summary>
        public static string VisarDominios {
            get {
                return ResourceManager.GetString("VisarDominios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 226.
        /// </summary>
        public static string VisarGraficos {
            get {
                return ResourceManager.GetString("VisarGraficos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 231.
        /// </summary>
        public static string VisarTopografia {
            get {
                return ResourceManager.GetString("VisarTopografia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 227.
        /// </summary>
        public static string VisarValuaciones {
            get {
                return ResourceManager.GetString("VisarValuaciones", resourceCulture);
            }
        }
    }
}
