//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoSit.Data.BusinessEntities.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FuncionesTramite {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FuncionesTramite() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoSit.Data.BusinessEntities.GlobalResources.FuncionesTramite", typeof(FuncionesTramite).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 531.
        /// </summary>
        public static string ActualizarInforme {
            get {
                return ResourceManager.GetString("ActualizarInforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 487.
        /// </summary>
        public static string AnexarInforme {
            get {
                return ResourceManager.GetString("AnexarInforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 530.
        /// </summary>
        public static string AnexarInformeFirmado {
            get {
                return ResourceManager.GetString("AnexarInformeFirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 527.
        /// </summary>
        public static string AprobarTramite {
            get {
                return ResourceManager.GetString("AprobarTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 484.
        /// </summary>
        public static string Consultar {
            get {
                return ResourceManager.GetString("Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 449.
        /// </summary>
        public static string Derivar {
            get {
                return ResourceManager.GetString("Derivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 462.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 454.
        /// </summary>
        public static string Finalizar {
            get {
                return ResourceManager.GetString("Finalizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 465.
        /// </summary>
        public static string ImprimirHojaRuta {
            get {
                return ResourceManager.GetString("ImprimirHojaRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 451.
        /// </summary>
        public static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 463.
        /// </summary>
        public static string Nuevo {
            get {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 456.
        /// </summary>
        public static string Observar {
            get {
                return ResourceManager.GetString("Observar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 515.
        /// </summary>
        public static string Presentar {
            get {
                return ResourceManager.GetString("Presentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 514.
        /// </summary>
        public static string Procesar {
            get {
                return ResourceManager.GetString("Procesar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 518.
        /// </summary>
        public static string Reasignar {
            get {
                return ResourceManager.GetString("Reasignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 450.
        /// </summary>
        public static string Recibir {
            get {
                return ResourceManager.GetString("Recibir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 461.
        /// </summary>
        public static string Reingresar {
            get {
                return ResourceManager.GetString("Reingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 524.
        /// </summary>
        public static string ReservarNomenclaturasPartidas {
            get {
                return ResourceManager.GetString("ReservarNomenclaturasPartidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 529.
        /// </summary>
        public static string ReservarNumeroPlano {
            get {
                return ResourceManager.GetString("ReservarNumeroPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 523.
        /// </summary>
        public static string SolicitarReserva {
            get {
                return ResourceManager.GetString("SolicitarReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 519.
        /// </summary>
        public static string VisarDatosCatastrales {
            get {
                return ResourceManager.GetString("VisarDatosCatastrales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 525.
        /// </summary>
        public static string VisarDatosDominiales {
            get {
                return ResourceManager.GetString("VisarDatosDominiales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 528.
        /// </summary>
        public static string VisarDatosTopograficos {
            get {
                return ResourceManager.GetString("VisarDatosTopograficos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 526.
        /// </summary>
        public static string VisarDatosValuativos {
            get {
                return ResourceManager.GetString("VisarDatosValuativos", resourceCulture);
            }
        }
    }
}
