//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoSit.Data.BusinessEntities.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KeysDatosEspecificos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeysDatosEspecificos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoSit.Data.BusinessEntities.GlobalResources.KeysDatosEspecificos", typeof(KeysDatosEspecificos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyClaseParcela.
        /// </summary>
        public static string KeyClaseParcela {
            get {
                return ResourceManager.GetString("KeyClaseParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyDominios.
        /// </summary>
        public static string KeyDominios {
            get {
                return ResourceManager.GetString("KeyDominios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyEstadoMensura.
        /// </summary>
        public static string KeyEstadoMensura {
            get {
                return ResourceManager.GetString("KeyEstadoMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyEstadoParcela.
        /// </summary>
        public static string KeyEstadoParcela {
            get {
                return ResourceManager.GetString("KeyEstadoParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyIdManzana.
        /// </summary>
        public static string KeyIdManzana {
            get {
                return ResourceManager.GetString("KeyIdManzana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyIdMensura.
        /// </summary>
        public static string KeyIdMensura {
            get {
                return ResourceManager.GetString("KeyIdMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyIdParcela.
        /// </summary>
        public static string KeyIdParcela {
            get {
                return ResourceManager.GetString("KeyIdParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyIdTipoUnidadTributaria.
        /// </summary>
        public static string KeyIdTipoUnidadTributaria {
            get {
                return ResourceManager.GetString("KeyIdTipoUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyIdUnidadTributaria.
        /// </summary>
        public static string KeyIdUnidadTributaria {
            get {
                return ResourceManager.GetString("KeyIdUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyOperacion.
        /// </summary>
        public static string KeyOperacion {
            get {
                return ResourceManager.GetString("KeyOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyPorcentajeCopropiedad.
        /// </summary>
        public static string KeyPorcentajeCopropiedad {
            get {
                return ResourceManager.GetString("KeyPorcentajeCopropiedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeySuperficieParcela.
        /// </summary>
        public static string KeySuperficieParcela {
            get {
                return ResourceManager.GetString("KeySuperficieParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeySuperficieUT.
        /// </summary>
        public static string KeySuperficieUT {
            get {
                return ResourceManager.GetString("KeySuperficieUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyTipoMensura.
        /// </summary>
        public static string KeyTipoMensura {
            get {
                return ResourceManager.GetString("KeyTipoMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyTipoParcela.
        /// </summary>
        public static string KeyTipoParcela {
            get {
                return ResourceManager.GetString("KeyTipoParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyUnidadFuncional.
        /// </summary>
        public static string KeyUnidadFuncional {
            get {
                return ResourceManager.GetString("KeyUnidadFuncional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyValuacion.
        /// </summary>
        public static string KeyValuacion {
            get {
                return ResourceManager.GetString("KeyValuacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyVigenciaDesde.
        /// </summary>
        public static string KeyVigenciaDesde {
            get {
                return ResourceManager.GetString("KeyVigenciaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyVigenciaHasta.
        /// </summary>
        public static string KeyVigenciaHasta {
            get {
                return ResourceManager.GetString("KeyVigenciaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string LabelNombre {
            get {
                return ResourceManager.GetString("LabelNombre", resourceCulture);
            }
        }
    }
}
