//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoSit.Data.BusinessEntities.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoSit.Data.BusinessEntities.GlobalResources.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se abrió el Libro Diario correctamente.
        /// </summary>
        public static string AbrirLibroDiarioOK {
            get {
                return ResourceManager.GetString("AbrirLibroDiarioOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Feriado correctamente..
        /// </summary>
        public static string AgregarFeriadosOK {
            get {
                return ResourceManager.GetString("AgregarFeriadosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Horario correctamente..
        /// </summary>
        public static string AgregarHorariosOK {
            get {
                return ResourceManager.GetString("AgregarHorariosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agrego la Mensura Correctamente.
        /// </summary>
        public static string AgregarMensuraOK {
            get {
                return ResourceManager.GetString("AgregarMensuraOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Perfil correctamente..
        /// </summary>
        public static string AgregarPerfilesOK {
            get {
                return ResourceManager.GetString("AgregarPerfilesOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Plano correctamente..
        /// </summary>
        public static string AgregarPlanoOK {
            get {
                return ResourceManager.GetString("AgregarPlanoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregaron los Planos correctamente..
        /// </summary>
        public static string AgregarPlanosOK {
            get {
                return ResourceManager.GetString("AgregarPlanosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Remito Correctamente.
        /// </summary>
        public static string AgregarRemitoOK {
            get {
                return ResourceManager.GetString("AgregarRemitoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el registro correctamente..
        /// </summary>
        public static string AgregarTablasAuxOK {
            get {
                return ResourceManager.GetString("AgregarTablasAuxOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Usuario correctamente..
        /// </summary>
        public static string AgregarUsuariosOK {
            get {
                return ResourceManager.GetString("AgregarUsuariosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el el alfanumerico de Parcelas correctamente..
        /// </summary>
        public static string AltaAlfanumericodeParcelasyPosesionesOK {
            get {
                return ResourceManager.GetString("AltaAlfanumericodeParcelasyPosesionesOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Atributo correctamente..
        /// </summary>
        public static string AltaAtributoOK {
            get {
                return ResourceManager.GetString("AltaAtributoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Certificado correctamente..
        /// </summary>
        public static string AltaCertificadosOK {
            get {
                return ResourceManager.GetString("AltaCertificadosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Control Tecnico correctamente..
        /// </summary>
        public static string AltaControlTecnicoOK {
            get {
                return ResourceManager.GetString("AltaControlTecnicoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Acta correctamente..
        /// </summary>
        public static string AltadeActasOK {
            get {
                return ResourceManager.GetString("AltadeActasOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Inspeccion correctamente..
        /// </summary>
        public static string AltadeInspeccionOK {
            get {
                return ResourceManager.GetString("AltadeInspeccionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Inspector correctamente..
        /// </summary>
        public static string AltadeinspectoresOK {
            get {
                return ResourceManager.GetString("AltadeinspectoresOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agrego la Parcela Mensura correctamente.
        /// </summary>
        public static string AltaDeParcelaMensuraOK {
            get {
                return ResourceManager.GetString("AltaDeParcelaMensuraOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó la Parcela Destino correctamente..
        /// </summary>
        public static string AltadeParcelasDestinoOK {
            get {
                return ResourceManager.GetString("AltadeParcelasDestinoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó la Parcela Origen correctamente..
        /// </summary>
        public static string AltadeParcelasOrigenOK {
            get {
                return ResourceManager.GetString("AltadeParcelasOrigenOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó la Persona correctamente..
        /// </summary>
        public static string AltadePersonasOK {
            get {
                return ResourceManager.GetString("AltadePersonasOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó la Profesión correctamente..
        /// </summary>
        public static string AltadeProfesionOK {
            get {
                return ResourceManager.GetString("AltadeProfesionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Registro correctamente..
        /// </summary>
        public static string AltaderegistrosOK {
            get {
                return ResourceManager.GetString("AltaderegistrosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Resultado de Busqueda correctamente..
        /// </summary>
        public static string AltadeResultadodeBusquedaOK {
            get {
                return ResourceManager.GetString("AltadeResultadodeBusquedaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Tramite correctamente..
        /// </summary>
        public static string AltadeTramitesOK {
            get {
                return ResourceManager.GetString("AltadeTramitesOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Documento correctamente..
        /// </summary>
        public static string AltaDocumentoOK {
            get {
                return ResourceManager.GetString("AltaDocumentoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Documento Parcela correctamente..
        /// </summary>
        public static string AltaDocumentosParcelaOK {
            get {
                return ResourceManager.GetString("AltaDocumentosParcelaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Documento Unidad Tributaria correctamente..
        /// </summary>
        public static string AltaDocumentosUnidadTributariaOK {
            get {
                return ResourceManager.GetString("AltaDocumentosUnidadTributariaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Domicilio correctamente..
        /// </summary>
        public static string AltaDomicilioOK {
            get {
                return ResourceManager.GetString("AltaDomicilioOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Dominio correctamente..
        /// </summary>
        public static string AltaDominioOK {
            get {
                return ResourceManager.GetString("AltaDominioOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Estado correctamente..
        /// </summary>
        public static string AltaEstadoOK {
            get {
                return ResourceManager.GetString("AltaEstadoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Expediente Obra correctamente..
        /// </summary>
        public static string AltaExpedientesObraOK {
            get {
                return ResourceManager.GetString("AltaExpedientesObraOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Inspeccion correctamente..
        /// </summary>
        public static string AltaInspeccionOK {
            get {
                return ResourceManager.GetString("AltaInspeccionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó la Liquidacion correctamente..
        /// </summary>
        public static string AltaLiquidacionOK {
            get {
                return ResourceManager.GetString("AltaLiquidacionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Mantenedor Unidad Tributaria correctamente..
        /// </summary>
        public static string AltaMantenedorUnidadTributariaOK {
            get {
                return ResourceManager.GetString("AltaMantenedorUnidadTributariaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó la Nomenclatura correctamente..
        /// </summary>
        public static string AltaNomenclaturaOK {
            get {
                return ResourceManager.GetString("AltaNomenclaturaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó la Observación correctamente..
        /// </summary>
        public static string AltaObservacionOK {
            get {
                return ResourceManager.GetString("AltaObservacionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó la Persona correctamente..
        /// </summary>
        public static string AltaPersonaOK {
            get {
                return ResourceManager.GetString("AltaPersonaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Responsable Fiscal correctamente..
        /// </summary>
        public static string AltaResponsableFiscalOK {
            get {
                return ResourceManager.GetString("AltaResponsableFiscalOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó la Superficie correctamente..
        /// </summary>
        public static string AltaSuperficieOK {
            get {
                return ResourceManager.GetString("AltaSuperficieOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el Titular correctamente..
        /// </summary>
        public static string AltaTitularOK {
            get {
                return ResourceManager.GetString("AltaTitularOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó la Ubicacion correctamente..
        /// </summary>
        public static string AltaUbicacionObraOK {
            get {
                return ResourceManager.GetString("AltaUbicacionObraOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó la Unidad Tributaria correctamente..
        /// </summary>
        public static string AltaUnidadesTributariasOK {
            get {
                return ResourceManager.GetString("AltaUnidadesTributariasOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Certificado correctamente..
        /// </summary>
        public static string BajaCertificadosOK {
            get {
                return ResourceManager.GetString("BajaCertificadosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Control Tecnico correctamente..
        /// </summary>
        public static string BajaControlTecnicoOK {
            get {
                return ResourceManager.GetString("BajaControlTecnicoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Acta correctamente..
        /// </summary>
        public static string BajadeactasOK {
            get {
                return ResourceManager.GetString("BajadeactasOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Atributo correctamente..
        /// </summary>
        public static string BajadeAtributosOK {
            get {
                return ResourceManager.GetString("BajadeAtributosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito la Inspeccion correctamente..
        /// </summary>
        public static string BajadeInspeccionOK {
            get {
                return ResourceManager.GetString("BajadeInspeccionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Inspector correctamente..
        /// </summary>
        public static string BajadeinspectoresOK {
            get {
                return ResourceManager.GetString("BajadeinspectoresOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito la Liquidacion correctamente..
        /// </summary>
        public static string BajadeLiquidacionOK {
            get {
                return ResourceManager.GetString("BajadeLiquidacionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito la Parcela Destino correctamente..
        /// </summary>
        public static string BajadeParcelasDestinoOK {
            get {
                return ResourceManager.GetString("BajadeParcelasDestinoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito la Parcela Origen correctamente..
        /// </summary>
        public static string BajadeParcelasOrigenOK {
            get {
                return ResourceManager.GetString("BajadeParcelasOrigenOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito la Persona correctamente..
        /// </summary>
        public static string BajadePersonasOK {
            get {
                return ResourceManager.GetString("BajadePersonasOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito la Profesion correctamente..
        /// </summary>
        public static string BajadeProfesionOK {
            get {
                return ResourceManager.GetString("BajadeProfesionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Registro correctamente..
        /// </summary>
        public static string BajadeRegistrosOK {
            get {
                return ResourceManager.GetString("BajadeRegistrosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Resultado de Busqueda correctamente..
        /// </summary>
        public static string BajadeResultadodeBusquedaOK {
            get {
                return ResourceManager.GetString("BajadeResultadodeBusquedaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Tramite correctamente..
        /// </summary>
        public static string BajadeTramiteOK {
            get {
                return ResourceManager.GetString("BajadeTramiteOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Documento correctamente..
        /// </summary>
        public static string BajaDocumentoOK {
            get {
                return ResourceManager.GetString("BajaDocumentoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Documento Parcela correctamente..
        /// </summary>
        public static string BajaDocumentosParcelaOK {
            get {
                return ResourceManager.GetString("BajaDocumentosParcelaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Atributo correctamente..
        /// </summary>
        public static string BajaDocumentosUnidadTributariaOK {
            get {
                return ResourceManager.GetString("BajaDocumentosUnidadTributariaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Domicilio correctamente..
        /// </summary>
        public static string BajaDomicilioOK {
            get {
                return ResourceManager.GetString("BajaDomicilioOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Dominio correctamente..
        /// </summary>
        public static string BajaDominioOK {
            get {
                return ResourceManager.GetString("BajaDominioOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Expediente Obra correctamente..
        /// </summary>
        public static string BajaExpedientedeObraOK {
            get {
                return ResourceManager.GetString("BajaExpedientedeObraOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se eliminaron los Expedientes de Obra Correntamente..
        /// </summary>
        public static string BajaExpedientesObraOK {
            get {
                return ResourceManager.GetString("BajaExpedientesObraOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito la Liquidacion Correctamente..
        /// </summary>
        public static string BajaLiquidacionOK {
            get {
                return ResourceManager.GetString("BajaLiquidacionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Mantenedor Unidad Tributaria Correctamente..
        /// </summary>
        public static string BajaMantenedorUnidadTributariaOK {
            get {
                return ResourceManager.GetString("BajaMantenedorUnidadTributariaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito la Nomenclatura Correctamente..
        /// </summary>
        public static string BajaNomenclaturaOK {
            get {
                return ResourceManager.GetString("BajaNomenclaturaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito la Observacion Correctamente..
        /// </summary>
        public static string BajaObservacionOK {
            get {
                return ResourceManager.GetString("BajaObservacionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito la Persona Correctamente..
        /// </summary>
        public static string BajaPersonaOK {
            get {
                return ResourceManager.GetString("BajaPersonaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Responsable Fiscal Correctamente..
        /// </summary>
        public static string BajaResponsableFiscalOK {
            get {
                return ResourceManager.GetString("BajaResponsableFiscalOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito la Superficie Correctamente..
        /// </summary>
        public static string BajaSuperficieOK {
            get {
                return ResourceManager.GetString("BajaSuperficieOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Titular Correctamente..
        /// </summary>
        public static string BajaTitularOK {
            get {
                return ResourceManager.GetString("BajaTitularOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito la Ubicacion de Obra Correctamente..
        /// </summary>
        public static string BajaUbicacionObraOK {
            get {
                return ResourceManager.GetString("BajaUbicacionObraOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito la Unidad Tributaria Correctamente..
        /// </summary>
        public static string BajaUnidadesTributariasOK {
            get {
                return ResourceManager.GetString("BajaUnidadesTributariasOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se cerró el Libro Diario correctamente.
        /// </summary>
        public static string CerrarLibroDiarioOK {
            get {
                return ResourceManager.GetString("CerrarLibroDiarioOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato del archivo seleccionado inválido..
        /// </summary>
        public static string ColeccionController_ImportarArchivoColeccion_FormatoInvalido {
            get {
                return ResourceManager.GetString("ColeccionController_ImportarArchivoColeccion_FormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre [{0}] ya existe, por favor ingrese uno nuevo..
        /// </summary>
        public static string ColeccionController_NombreColeccionExistente {
            get {
                return ResourceManager.GetString("ColeccionController_NombreColeccionExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se confirmo el Tramite Correctamente.
        /// </summary>
        public static string ConfirmarTramiteOK {
            get {
                return ResourceManager.GetString("ConfirmarTramiteOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Feriado Correctamente..
        /// </summary>
        public static string EliminarFeriadosOK {
            get {
                return ResourceManager.GetString("EliminarFeriadosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Horario Correctamente..
        /// </summary>
        public static string EliminarHorariosOK {
            get {
                return ResourceManager.GetString("EliminarHorariosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Inspector Correctamente..
        /// </summary>
        public static string EliminarInspectoresOK {
            get {
                return ResourceManager.GetString("EliminarInspectoresOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se elimino la Mensura Correctamente.
        /// </summary>
        public static string EliminarMensuraOK {
            get {
                return ResourceManager.GetString("EliminarMensuraOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito la Parcela Destino Correctamente..
        /// </summary>
        public static string EliminarParcelaDestinoOK {
            get {
                return ResourceManager.GetString("EliminarParcelaDestinoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito la Parcela Origen Correctamente..
        /// </summary>
        public static string EliminarParcelaOrigenOK {
            get {
                return ResourceManager.GetString("EliminarParcelaOrigenOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Perfil Correctamente..
        /// </summary>
        public static string EliminarPerfilesOK {
            get {
                return ResourceManager.GetString("EliminarPerfilesOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el registro Correctamente..
        /// </summary>
        public static string EliminarTablaAuxOK {
            get {
                return ResourceManager.GetString("EliminarTablaAuxOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se quito el Usuario Correctamente..
        /// </summary>
        public static string EliminarUsuariosOK {
            get {
                return ResourceManager.GetString("EliminarUsuariosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se Exporto Correctamente..
        /// </summary>
        public static string ExportarOK {
            get {
                return ResourceManager.GetString("ExportarOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se guardo el Expediente Obra Correctamente..
        /// </summary>
        public static string GuardarExpedienteObraOK {
            get {
                return ResourceManager.GetString("GuardarExpedienteObraOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string LoginOK {
            get {
                return ResourceManager.GetString("LoginOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Acta Correctamente..
        /// </summary>
        public static string ModificaciondeActasOK {
            get {
                return ResourceManager.GetString("ModificaciondeActasOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Atributo Correctamente.
        /// </summary>
        public static string ModificaciondeAtributosOK {
            get {
                return ResourceManager.GetString("ModificaciondeAtributosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Resultado de Busqueda Correctamente..
        /// </summary>
        public static string ModificaciondeResultadodeBusquedaOK {
            get {
                return ResourceManager.GetString("ModificaciondeResultadodeBusquedaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Expediente Obra Correctamente..
        /// </summary>
        public static string ModificacionExpedientesObraOK {
            get {
                return ResourceManager.GetString("ModificacionExpedientesObraOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Certificado Correctamente..
        /// </summary>
        public static string ModificarCertificadosOK {
            get {
                return ResourceManager.GetString("ModificarCertificadosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Control Tecnico Correctamente..
        /// </summary>
        public static string ModificarControlTecnicoOK {
            get {
                return ResourceManager.GetString("ModificarControlTecnicoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Documento Correctamente..
        /// </summary>
        public static string ModificarDocumentoOK {
            get {
                return ResourceManager.GetString("ModificarDocumentoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Documento Parcela Correctamente..
        /// </summary>
        public static string ModificarDocumentosParcelaOK {
            get {
                return ResourceManager.GetString("ModificarDocumentosParcelaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Documento Unidad Tributaria Correctamente..
        /// </summary>
        public static string ModificarDocumentosUnidadTributariaOK {
            get {
                return ResourceManager.GetString("ModificarDocumentosUnidadTributariaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Domicilio Correctamente..
        /// </summary>
        public static string ModificarDomicilioOK {
            get {
                return ResourceManager.GetString("ModificarDomicilioOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Domicio Correctamente..
        /// </summary>
        public static string ModificarDominioOK {
            get {
                return ResourceManager.GetString("ModificarDominioOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Estado Correctamente..
        /// </summary>
        public static string ModificarEstadoOK {
            get {
                return ResourceManager.GetString("ModificarEstadoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Feriado Correctamente..
        /// </summary>
        public static string ModificarFeriadosOK {
            get {
                return ResourceManager.GetString("ModificarFeriadosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Horario Correctamente..
        /// </summary>
        public static string ModificarHorariosOK {
            get {
                return ResourceManager.GetString("ModificarHorariosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico la Inspeccion Correctamente..
        /// </summary>
        public static string ModificarInspeccionOK {
            get {
                return ResourceManager.GetString("ModificarInspeccionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modificaron los Inspectores Correctamente..
        /// </summary>
        public static string ModificarinspectoresOK {
            get {
                return ResourceManager.GetString("ModificarinspectoresOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico la Liquidacion Correctamente..
        /// </summary>
        public static string ModificarLiquidacionOK {
            get {
                return ResourceManager.GetString("ModificarLiquidacionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Mantenedor Parcelario Correctamente.
        /// </summary>
        public static string ModificarMantenedorParcelarioOK {
            get {
                return ResourceManager.GetString("ModificarMantenedorParcelarioOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Mantenedor Unidad Tributaria Correctamente..
        /// </summary>
        public static string ModificarMantenedorUnidadTributariaOK {
            get {
                return ResourceManager.GetString("ModificarMantenedorUnidadTributariaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico la Mensura Correctamente.
        /// </summary>
        public static string ModificarMensuraOK {
            get {
                return ResourceManager.GetString("ModificarMensuraOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico la Nomenclatura Correctamente..
        /// </summary>
        public static string ModificarNomenclaturaOK {
            get {
                return ResourceManager.GetString("ModificarNomenclaturaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico la Observacion Correctamente.
        /// </summary>
        public static string ModificarObservacionOK {
            get {
                return ResourceManager.GetString("ModificarObservacionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modificaron los Parametros Generales Correctamente.
        /// </summary>
        public static string ModificarParametrosGeneralesOK {
            get {
                return ResourceManager.GetString("ModificarParametrosGeneralesOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modificaron el Perfil Correctamente..
        /// </summary>
        public static string ModificarPerfilesOK {
            get {
                return ResourceManager.GetString("ModificarPerfilesOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico la Persona Correctamente.
        /// </summary>
        public static string ModificarPersonasOK {
            get {
                return ResourceManager.GetString("ModificarPersonasOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico la Profesion Correctamente.
        /// </summary>
        public static string ModificarProfesionOK {
            get {
                return ResourceManager.GetString("ModificarProfesionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modificaron losRegistros Correctamente..
        /// </summary>
        public static string ModificarRegistreosOK {
            get {
                return ResourceManager.GetString("ModificarRegistreosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modificaron los Responsables Fiscales Correctamente..
        /// </summary>
        public static string ModificarResponsableFiscalOK {
            get {
                return ResourceManager.GetString("ModificarResponsableFiscalOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico la Superficie Correctamente..
        /// </summary>
        public static string ModificarSuperficieOK {
            get {
                return ResourceManager.GetString("ModificarSuperficieOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Registro Correctamente..
        /// </summary>
        public static string ModificarTablasAuxOK {
            get {
                return ResourceManager.GetString("ModificarTablasAuxOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Titular Correctamente..
        /// </summary>
        public static string ModificarTitularOK {
            get {
                return ResourceManager.GetString("ModificarTitularOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Tramite Correctamente..
        /// </summary>
        public static string ModificarTramitesOK {
            get {
                return ResourceManager.GetString("ModificarTramitesOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico el Usuario Correctamente..
        /// </summary>
        public static string ModificarUsuariosOK {
            get {
                return ResourceManager.GetString("ModificarUsuariosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string NoAutorizadoOK {
            get {
                return ResourceManager.GetString("NoAutorizadoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se procesaron las transacciones correctamente..
        /// </summary>
        public static string ProcesadoTransaccionesOK {
            get {
                return ResourceManager.GetString("ProcesadoTransaccionesOK", resourceCulture);
            }
        }
    }
}
