//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoSit.Data.BusinessEntities.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ObjetosTramites {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObjetosTramites() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoSit.Data.BusinessEntities.GlobalResources.ObjetosTramites", typeof(ObjetosTramites).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.
        /// </summary>
        public static string CambioTitularidad {
            get {
                return ResourceManager.GetString("CambioTitularidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string CertificadoValuacionFiscal {
            get {
                return ResourceManager.GetString("CertificadoValuacionFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        public static string ConstanciaNomenclaturaCatastral {
            get {
                return ResourceManager.GetString("ConstanciaNomenclaturaCatastral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        public static string ConsultaPlanoyVistasDeDocumentacion {
            get {
                return ResourceManager.GetString("ConsultaPlanoyVistasDeDocumentacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        public static string ConsultaReclamoActuacionEnTramite {
            get {
                return ResourceManager.GetString("ConsultaReclamoActuacionEnTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        public static string ConsultaSolicitudCopiaHistoricadeMinutaRPI {
            get {
                return ResourceManager.GetString("ConsultaSolicitudCopiaHistoricadeMinutaRPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string CopiasHeliograficas {
            get {
                return ResourceManager.GetString("CopiasHeliograficas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.
        /// </summary>
        public static string CopiasVarias {
            get {
                return ResourceManager.GetString("CopiasVarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string DerechoDeSuperficie {
            get {
                return ResourceManager.GetString("DerechoDeSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        public static string EscaneoPlanoMensura {
            get {
                return ResourceManager.GetString("EscaneoPlanoMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        public static string FotoInterpretacion {
            get {
                return ResourceManager.GetString("FotoInterpretacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        public static string InformeCatastral {
            get {
                return ResourceManager.GetString("InformeCatastral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        public static string InformedeEstadoDominial {
            get {
                return ResourceManager.GetString("InformedeEstadoDominial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string InformedePadronJuridicoValuatorio {
            get {
                return ResourceManager.GetString("InformedePadronJuridicoValuatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        public static string InformeDescripcionInmuebleMedidasyLinderos {
            get {
                return ResourceManager.GetString("InformeDescripcionInmuebleMedidasyLinderos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        public static string InformeRespuestaAOficios {
            get {
                return ResourceManager.GetString("InformeRespuestaAOficios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string InformeUbicacionCartografica {
            get {
                return ResourceManager.GetString("InformeUbicacionCartografica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Mensura {
            get {
                return ResourceManager.GetString("Mensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string MensuraParaPrescripcionAdquisitiva {
            get {
                return ResourceManager.GetString("MensuraParaPrescripcionAdquisitiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        public static string MensurasOficialesModificaciondePlanoAprobado {
            get {
                return ResourceManager.GetString("MensurasOficialesModificaciondePlanoAprobado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string MensuraSubdivisionParaDerechoRealPropiedadHorizontal {
            get {
                return ResourceManager.GetString("MensuraSubdivisionParaDerechoRealPropiedadHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string MensuraSubdivisionyUnificacion {
            get {
                return ResourceManager.GetString("MensuraSubdivisionyUnificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string MensuraUnificacionySubdivision {
            get {
                return ResourceManager.GetString("MensuraUnificacionySubdivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string MensuraySubdivision {
            get {
                return ResourceManager.GetString("MensuraySubdivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string MensurayUnificacion {
            get {
                return ResourceManager.GetString("MensurayUnificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        public static string ModificacionPlanoAprobado {
            get {
                return ResourceManager.GetString("ModificacionPlanoAprobado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        public static string OtrosInformesVarios {
            get {
                return ResourceManager.GetString("OtrosInformesVarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        public static string PlanoAprobado {
            get {
                return ResourceManager.GetString("PlanoAprobado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string PropiedadHorizontalEspecial {
            get {
                return ResourceManager.GetString("PropiedadHorizontalEspecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string PropiedadHorizontalRetrotraibleEstadoParcelarioAnterior {
            get {
                return ResourceManager.GetString("PropiedadHorizontalRetrotraibleEstadoParcelarioAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string ServidumbreDePaso {
            get {
                return ResourceManager.GetString("ServidumbreDePaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        public static string ServidumbreParaElectroductoGasoductoOleoducto {
            get {
                return ResourceManager.GetString("ServidumbreParaElectroductoGasoductoOleoducto", resourceCulture);
            }
        }
    }
}
