//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GeoSit.Web.Api.inmAvaluoMasivo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Avaluo Masivo de InmuebleBinding", Namespace="urn:inmAvaluoMasivo")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(avaluos_inmuebles))]
    public partial class AvaluoMasivodeInmueble : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback avaluomasivoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AvaluoMasivodeInmueble() {
            this.Url = global::GeoSit.Web.Api.Properties.Settings.Default.GeoSit_Web_Api_inmAvaluoMasivo_Avaluo_Masivo_de_Inmueble;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event avaluomasivoCompletedEventHandler avaluomasivoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:inmuebles#avaluomasivo", RequestNamespace="urn:inmAvaluoMasivo", ResponseNamespace="urn:inmAvaluoMasivo")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string avaluomasivo(datos_inmueble datos_inmueble, avaluos_inmuebles[] avaluos_inmuebles) {
            object[] results = this.Invoke("avaluomasivo", new object[] {
                        datos_inmueble,
                        avaluos_inmuebles});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void avaluomasivoAsync(datos_inmueble datos_inmueble, avaluos_inmuebles[] avaluos_inmuebles) {
            this.avaluomasivoAsync(datos_inmueble, avaluos_inmuebles, null);
        }
        
        /// <remarks/>
        public void avaluomasivoAsync(datos_inmueble datos_inmueble, avaluos_inmuebles[] avaluos_inmuebles, object userState) {
            if ((this.avaluomasivoOperationCompleted == null)) {
                this.avaluomasivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnavaluomasivoOperationCompleted);
            }
            this.InvokeAsync("avaluomasivo", new object[] {
                        datos_inmueble,
                        avaluos_inmuebles}, this.avaluomasivoOperationCompleted, userState);
        }
        
        private void OnavaluomasivoOperationCompleted(object arg) {
            if ((this.avaluomasivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.avaluomasivoCompleted(this, new avaluomasivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:inmAvaluoMasivo")]
    public partial class datos_inmueble {
        
        private int vigenciaField;
        
        /// <remarks/>
        public int vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:inmAvaluoMasivo")]
    public partial class avaluos_inmuebles {
        
        private string obj_idField;
        
        private string suptField;
        
        private string supmField;
        
        private string avaltField;
        
        private string avalmField;
        
        private int regimenField;
        
        /// <remarks/>
        public string obj_id {
            get {
                return this.obj_idField;
            }
            set {
                this.obj_idField = value;
            }
        }
        
        /// <remarks/>
        public string supt {
            get {
                return this.suptField;
            }
            set {
                this.suptField = value;
            }
        }
        
        /// <remarks/>
        public string supm {
            get {
                return this.supmField;
            }
            set {
                this.supmField = value;
            }
        }
        
        /// <remarks/>
        public string avalt {
            get {
                return this.avaltField;
            }
            set {
                this.avaltField = value;
            }
        }
        
        /// <remarks/>
        public string avalm {
            get {
                return this.avalmField;
            }
            set {
                this.avalmField = value;
            }
        }
        
        /// <remarks/>
        public int regimen {
            get {
                return this.regimenField;
            }
            set {
                this.regimenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void avaluomasivoCompletedEventHandler(object sender, avaluomasivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class avaluomasivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal avaluomasivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591