//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoSit.Web.Api.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("asdasd")]
        public string DB {
            get {
                return ((string)(this["DB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://emaw70512.hopto.org/samws/inmBaja.php")]
        public string GeoSit_Web_Api_inmBaja_Baja_de_Inmueble {
            get {
                return ((string)(this["GeoSit_Web_Api_inmBaja_Baja_de_Inmueble"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://emaw70512.hopto.org/samws/inmEdita.php")]
        public string GeoSit_Web_Api_inmEdita_Alta_y_Modificación_de_Inmueble {
            get {
                return ((string)(this["GeoSit_Web_Api_inmEdita_Alta_y_Modificación_de_Inmueble"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://emaw70512.hopto.org/samws/inmBajaPedido.php")]
        public string GeoSit_Web_Api_inmBajaPedido_Baja_de_Inmueble {
            get {
                return ((string)(this["GeoSit_Web_Api_inmBajaPedido_Baja_de_Inmueble"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://emaw70512.hopto.org/samws/inmAvaluo.php")]
        public string GeoSit_Web_Api_inmAvaluo_Avaluo_de_Inmueble {
            get {
                return ((string)(this["GeoSit_Web_Api_inmAvaluo_Avaluo_de_Inmueble"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://emaw70512.hopto.org/samws/inmAvaluoMasivo.php")]
        public string GeoSit_Web_Api_inmAvaluoMasivo_Avaluo_Masivo_de_Inmueble {
            get {
                return ((string)(this["GeoSit_Web_Api_inmAvaluoMasivo_Avaluo_Masivo_de_Inmueble"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://emaw70512.hopto.org/samws/inmAvaluoMasivo.php")]
        public string GeoSit_Web_Api_CustomServices_Avaluo_Masivo_de_Inmueble {
            get {
                return ((string)(this["GeoSit_Web_Api_CustomServices_Avaluo_Masivo_de_Inmueble"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:3171/DGCeITService.asmx")]
        public string GeoSit_Web_Api_DGCeITServices_DGCeITService {
            get {
                return ((string)(this["GeoSit_Web_Api_DGCeITServices_DGCeITService"]));
            }
        }
    }
}
