CREATE TABLE LOG_IF_RENTAS
(       
    ID_LOG NUMBER(20) NOT NULL PRIMARY KEY,                
    ID_TRANSACCION NUMBER(5) NOT NULL,
    ID_PARCELA NUMBER(19),
    PARTIDA VARCHAR2(20),
    FECHA DATE NOT NULL,
    OPERACION VARCHAR2(50),
    WEB_SERVICE VARCHAR2(50),    
    WEB_SERVICE_CLASS VARCHAR2(255),
    PARAMETROS CLOB,          
    RESULTADO CLOB,
    ESTADO SMALLINT
);